Hennepin-County/MAXIS-scripts

admin/individual-recertification-notices.vbs
admin/review-report.vbs

I was able to run this successfully and send out notices and capture the detail on the spreadsheet - so all the good things we want. 
I had two errors in the run;
1. The very las statistics didn't work because the automation around statistics uses the 'Table1' name assuming the information was in a table. It was not but this was fine. We lost no information and I was able to add it in manually after creating the table. 
2. I messed up and the CASE:NOTEs may indicate that information was sent to an AREP or SWKR when those aren't things. Basically I had the blanking of variables out of the loop. Without a way to small batch test with this functionality - this month is just going to be a bit funky. It is fixed now and should work with no issue next time.
I am confident the second issues is …

#432 - Adding Appointment Notices to Review Report

---

notes/caf.vbs

This pull is only for the autofill of the following details of the CAF:
- Interview Date 
- Interview person
- Interview method (phone)
- Verifs Needed 
- CAF Qual 'Yes's 
- CAF Qual person if 'Yes'
I have a training case (298341) that has an interview script run on it. I will have a couple more once I add the developer mode to interview. Testing this will be easier once I do that as well - so I will let you know on that.

#515 NOTES CAF - Reading the details of previous notes for autofil in the CAF script run

---

MASTER FUNCTIONS LIBRARY.vbs
Test scripts/Casey/functions/erase_txt_files.vbs
admin/work-assignment-from-excel.vbs
notes/interview.vbs
utilities/complete-phone-caf.vbs
utilities/complete-phone-csr.vbs

This pull request will handle for two main items that are linked.
1. We need to review script created files in the MyDocs folder and delete old ones. This is a safety measure for complicated scripts but needs to be cleaned up regularly. 
2.  Since we use wshshell and objFSO in the main FuncLib run, we need to remove those seperate calls from the scripts. 
Updates for deleting old files. 
Every time the FuncLib is run the script will review 'MyDocs' to look for a file with the naming convention from Interview or Complete Phone CAF. It will then review for a txt file type and the date created. If the date was more than a week ago, the script will delete the file. 
Updates for the reserved variables and constants 
objFSO - variable for the FileScripting Object 
wshshell - variable for the …

#537 FUNC LIB - adding definition of FSO and MyDocs folder - Deleting old 'save your work' files

---

notes/interview.vbs

Sometimes when Job information is entered into the Interview script in the jobs area, people are entering $0 as the wage amount. Then when the script tries to do math for the Expedited Determination, it hits an overflow error because you can't divide by zero. Added an If statement to be sure that it isn't 0 before we continue.

#643 - NOTES - Interview - handling so we don't divide by zero

---

utilities/request-access-to-priv-case.vbs

Updates to make the Request access to PRIV case more informative.
Identifies if case is privileged to the foster care team or to a safe at home worker. This changes the email that is sent.
Also recommends using Teams instead of Email for if resident is on the phone.

#642 - UTILITIES - Request Access to PRIV Case

---

notes/application-received.vbs

Update made to change the interview date listed in the appointment notice to be a text field instead of an editbox so that no one can change it - ALSO, added a button to link to HSR manual page about On Demand which outlines this whole procedure and the automation.

#645 NOTES - App Recvd - Appt date to be text field with OD explanation

---

MASTER FUNCTIONS LIBRARY.vbs

Before writing the information into the panel, the lines need to be cleared. Update to the function to clear the text right away without an if statement.

#708 FuncLib - access_ADDR function - clear line of text

---

utilities/update-check-dates.vbs

Review how the script assesses the dates to move through the sequence of dates for income sources that are paid semi-monthly. 
A large part of this was also ensuring the script is recognizing that the days indicated as the regular monthly pay dates are viewed as numbers and not strings for correct comparison.

#728 - UTILITIES - Update Check Dates - bug on determining semi-monthly pay dates

---

actions/add-grh-rate-2-to-mmis.vbs

Counties using the DHS scripts require their global variables county code to have a lower case x 
(example: x105 used and not X105)
the var "current_county" reads from maxis as "X105". 
Using replace on line 123 resolves the issue of a lower case x in the global variables without needing to change other DHS scripts to make this script work. This should also have no effect on Hennepin running the code.

ACTIONS - grh rate 2, If statement never true

---

notes/interview.vbs

Added a dialog with information and references to the MFIP Orientation information in HSR Manual and the CM. 
This functionality will serve as a reminder and placeholder for where the MFIP Orientation should fit in the interview process. This functionality is not complete and will not enter a CASE/NOTE or provide directed support for completing this requirement but will get the process integrated into the script run. 
Future enhanced functionality support is in the works and should be testing in the next week or so.

#729 NOTES - Interview - Soft Release of MFIP Orientation Support

---

notes/caf.vbs

Added:
1. Back to self between each note to ensure MAXIS is moving in the right way.
2. report out about the attempts of the script in creating CASE NOTE in the save your work and script run lowdown.
3. Found a string/boolean issue with restore your work that might actually be the cause - reviewed variables and added resolution code for the boolean variables. 
4. Removed MFIP DVD functionality
5. Added a script run lowdown detail to dindicate if a script run is using restore your work for future error report review
All functionality is ready for review.

#749 - NOTES - CAF - Stability added for CASE NOTE functionality

---

notes/caf.vbs

The is the resolution to the bug that CK reported last week. This has only been reported once and is because non-numeric information was entered in a field that was expected to be only numeric. 
This functionality will 'zero out' any information gathered from fields that are not numeric.

#771 NOTES - CAF - ensure all exp det variables are numbers

---

admin/task-based-dail-capture.vbs

for cases that have no DAIL messages in the DAIL/PICK that meet the criteria of DAIL types the script is looking for.
Quick fix, that appears to be working. For some reason with the DAIL/PICK vs DAIL/DAIL the # of DAILs isn't always exiting the do. DAIL/PICK is not the typical way we look for these messages, but seems more stable, just different than DAIL/DAIL.

#801 ADMIN - TASK-BASED DAIL CAPTURE: Added additional handling

---

actions/transfer-case.vbs

- removed secondary worker 
- script end with message explaining in 4 months this will happen via automation
- Move the CASE:NOTE to a nested IF statement that indicates the XFER was successful but once we xfer we cannot case note anymore

ACTIONS TRANSFER CASE #393, 442, 443, 466, 759 & 769 multi issue branch 

---

COMPLETE LIST OF SCRIPTS.vbs
notes/returned-mail.vbs

927 NOTES - RETURNED MAIL - bug(s)

---

Test scripts/Casey/Utilities/delete-casey-entry-from-pending-table.vbs
notes/application-received.vbs
notes/caf.vbs
notes/expedited-determination.vbs

This commit includes:
- NOTES - Application Received to add any case that is pending SNAP, or pending Cash and SNAP is not ACTIVE. These are defaulted to being potentially Expedited
- NOTES - Expedited Determination - Uses the expedited determination to update the SQL Table with the actual information (makking some NOT Expedited.
- NOTES - CAF - Uses the expedited determination to update the SQL Table with the actual information (makking some NOT Expedited.
Still needed:
- NOTES - Interview - add the same functionality as CAF and Exp Det - this is currently branched in another pull request and needs to be resolved.
Testing will be tricky with this one and will require we monitor closely to ensure no issues.

#937 Adding pending cases to a SQL Table for ES Workflow

---

MASTER FUNCTIONS LIBRARY.vbs
locally-installed-files/SETTINGS - GLOBAL VARIABLES.vbs

This pull will require coordination of the change to the T Drive version of Global Variables as that is accessed locally.

#938 & #864 Master Functions Library - Move the Tester Call to Global Variables and change notes_on_addr verbiage

---

actions/check-edrs.vbs

Update needed for when a user presses POLI TEMP button is pushed in the main dialog. If the button is pressed, the bug occurs when the user is leaving the dialog. There is no way to get out of POLI TEMP.

#952 ACTIONS - CHECK EDRS: Bug in dialog loop

---

actions/ma-epd-ei-fiat.vbs

Previously all of the months in the budget needed to be MA-EPD to work correctly in the FIATer.
Updated the functionality to be able to identify an EPD month individually in the budget and only use the EPD month for the average AND only FIAT the months that are coded EPD.

#798 ACTIONS - MA EPD FIATer - allow partial MA EPD Budget cases to work 

---

deu/adh-info-and-hearing.vbs
deu/appeal-summary-completed.vbs
deu/atr-received.vbs
deu/bulk-match-cleared.vbs
deu/ebt-out-of-state.vbs
deu/match-cleared.vbs
deu/overpayment-claim-entered.vbs
deu/paris-match-cleared-CC-claim-entered.vbs
deu/paris-match-cleared.vbs

In the specialty teams Shelter and DEU the team name was listed in lieu of the worker signature and the worker signature has been added. After the script was released it was discovered that the workers will determine their worker signature with their teams and this is out of the scope of this project. The team name in the signature will be removed for the following scripts:
REMOVED - "DEBT ESTABLISHMENT UNIT 612-348-4290 PROMPTS 1-1-1"
NOTES - DEU-ADH INFO HEARING
NOTES - DEU-APPEAL SUMMARY COMPLETED
NOTES - DEU-ATR RECEIVED
BULK - DEU-MATCH CLEARED
NOTES - DEU-EBT OUT OF STATE
ACTIONS - DEU-MATCH CLEARED
ACTIONS - DEU-OVERPAYMENT CLAIM ENTERED
ACTIONS - DEU-PARIS MATCH CLEARED CC
ACTIONS - DEU-PARIS MATCH CLEARED

316 ensure worker signature is in all scripts that case/note

---

deu/appeal-summary-completed.vbs
deu/atr-received.vbs
deu/match-cleared.vbs
deu/overpayment-claim-entered.vbs
deu/paris-match-cleared-CC-claim-entered.vbs

Problem: issue reported with scripts case noting in the same case note. 
Resolution: add the PF3 back in between the case notes to ensure a new case note is entered in the following scripts:

#316 BUG due to removal of PF3 between case notes

---

dail/dail-scrubber.vbs

Adds a variable to define if we are in INQUIRY so specific DAIL scripts can stop if not able to write/update.
More work needed to evaluate the specific DAIL scripts. This will just put in place the functionality to know if we are in INQUIRY or not.

#476 DAIL Scrubber - Read if in INQUIRY

---

notes/overpayment.vbs

Removed duplicate code.
Added a exit for if the unique claim is blank.
Found an issue with the all_claim_numbers - line #232. duplicate of claim II and claim III was not added.

#1035 NOTES - OVERPAYMENT: Bug in writing the claim/note

---

notes/overpayment.vbs

To ensure that the information about collectible fits on the same line of the CASE/NOTE I had to change the note information from 'through' to 'thru'. I know this is more informal but the meaning is clear and it makes everything fit.

#1161 NOTES - Overpayment - include collectible selection

---

notes/avs.vbs

Updated create_TIKL to 11 days instead of 10 to be consistent with ONEsource manual to initiate a case review 10 calendar days AFTER an ad-hoc request was submitted in AVS.

#1284 avs tikl update

---

locally-installed-files/redirect-utilities-mmis-manual.vbs
locally-installed-files/redirect-utilities-one-source.vbs

Updated MMIS & OneSource redirect to run off of T drive instead of locally/github. Unsure whether lines 13-43 are necessary. Code appears to open website successfully without and lines 13-43 seem more applicable to github access/lack of access.

1273 remove bzst from mmis&one source redirects

---

MASTER FUNCTIONS LIBRARY.vbs
actions/full-interview.vbs
admin/testing_addr_shel_and_hest_functions.vbs
deu/atr-received.vbs
notes/health-care-evaluation.vbs
notes/interview.vbs
utilities/va-verification-request.vbs

I added EMWaitReady to the following scripts:
-  ACTIONS - FULL INTERVIEW: any members after the ACCESS DENIED members won't be added to array
-  DEU - ATR RECEIVED
-  NOTES - CAF
-  NOTES - INTERVIEW
-  UTILITIES - COMPLETE PHONE CAF - this has since been retired. No action needed.
-  UTILITIES - VA VERIFICATION REQUEST
-  HH_member_custom_dialog(HH_member_array)
I did not make these updates:
- TEST SCRIPTS- NOTES COUNTY PAID MEDI B - it looks like this script has been retired. 
-  Function autofill_editbox_from_MAXIS - panel_read_from = "MEMB" - Since HH_member_custom_dialog(HH_member_array) now includes EMWaitReady, I think this function should work in cases with access_denied but let me know if there are other changes needed.
I made these updates but they weren't specifically …

#702 memb 'access denied' issues in scripts and functions

---

Test scripts/Ilse/Restart scripts/BULK - restart IMIG.vbs
admin/resolve-hc-eomc-in-mmis.vbs
admin/track-autoclose-overpayments.vbs
notes/mfip-orientation.vbs
utilities/uc-verification-request.vbs

I updated the following scripts that were not initially identified in the issue but also contain access_denied_check. 
- resolve-hc-eomc-in-mmis
- admin\track-autoclose-overpayments
- notes\mfip-orientation
- Restart scripts\BULK - restart IMIG - I noted in commit but wasn't sure if this needed to be updated as it is in test scripts folder
- utilities\uc-verification-request

#702 memb 'access denied' issues in scripts and functions addl scripts

---

actions/ma-fiater-for-grh-msa.vbs

Prioritized this fix since we have a great group of testers in the Ex Parte workers and we want to get everything in place. 
The goal is only to end the script if the pay frequency in the HC Inc Estimate is blank on a UNEA panel. 
Added a script run lowdown piece so the error reporting has more detail

#1392 ACTIONS - MA Fiat MSA-GRH - end script if pop up is blank

---

COMPLETE LIST OF SCRIPTS.vbs
MASTER FUNCTIONS LIBRARY.vbs

When the desert island failed, the redirects didn't work quite right. 
Most of the changes were needed in the local redirects for the desert island, but the Func Lib and CLOS are updated monthly from GH, so we needed to update the GH files with desert island paths.

#1372 correct desert island paths in Func Lib and CLOS

---

notes/caf.vbs

There is logic issues in figuring out if we are at SR or ER for the programs with SRs. 
Currently GRH is showing an issue because it should allow an ER to process with no interview, but it didn't even think this was an ER BECAUSE the SR and ER are the same date.
More logic to ensure that we know what process GRH is at.

#1203 NOTES - CAF better handling for finding if GRH is at ER

---

MASTER FUNCTIONS LIBRARY.vbs

Stats update:
We need to set the script date and time for when the script actually stops and not when the worker presses 'OK' on the end message box. This is facilitated by setting the date and time to variables that are defined before the display of the messagebox. Then, it doesn't matter WHEN the information is written to the data table, it is set from the end of the script run functionality. 
Update to determine_program_and_case_status_from_case_curr
There was an issue when the program status was read from CASE/CURR - there was extra information in the variable. I could only find this on REIN status, this is because the MM YY are listed next to the REIN status on CASE/CURR
The fix just resets the status variable in the function when 'left, 4' is REIN. This way only 'REIN' will pass …

#1418 #1228 FuncLib updates to statistics and determine_prog_and_case_status

---

dail/postponed-expedited-snap-verifications.vbs

Added SPEC/MEMO functionality to script, more specifically:
1. Updated dialog validation for needed verifications
2. Added functionality to pull in verifications needed from CASE/NOTE
3. Added functionality to write information to SPEC/MEMO in a more readable format
I had a question around the cash_check and case_noting_intake_dates variables. These don't appear in the DAIL scrubber or this script so wasn't sure if they were an unintentional carryover.
I included logic to capture the case number from the CASE/NOTE that can be removed once finalized since the DAIL scrubber will capture this.

#363 DAIL - POSTPONED EXP SNAP VERIFICATIONS enhancement: Add MEMO to functionality

---

notes/caf.vbs
notes/expedited-determination.vbs
notes/interview.vbs

Updated Snap reference button including: button name, button var, and link to eliminate the word SNAP and use the correct applications link. Also updated instructions sheet to have the correct screenshots.

1469 replace snap button link

---

notes/health-care-evaluation.vbs

#1452 - Fixed a few typos related to presumptive eligibility
#1359 - Added functionality to navigate to STAT/REVW for CM + 1 through, and including, CM - 4 (but not past 07/23) to determine if a HC status code is present. For instances where the HC status code is present, script will default HC eval process to "Recertification".

#1452 & #1359 HC EVAL - Fix typos for presumptive eligibility and add functionality to determine if case is a recertification

---

utilities/all-scripts.vbs

If we update CLOS policy.reference item with a new policy, there are specific requirements that are fussy. This adds a check and message box to All Scripts to help support testing of these updates.

#1465 UTILITIES - All Scripts - add testing block of policy references

---

notes/caf.vbs

There is some testing info on line 6184 that I will remove before pulling in.
This is a unique situation and we need to 'force' it to test. A case number is also listed there that will work to test. You should be able to 'untrack the EMER' and if that is done, the APPL date will not be considered and the second form will go away.

#1443 NOTES - CAF - removing multiple dates if a program is 'unchecked' that caused the multiple dates

---

notes/case-discrepancy.vbs

-Reformatted case note header to be more specific by adding in discrepancy type and fit on 1 line. 
-New combo box in dialog for discrepancy type (handling: required to select or enter something)
-Added case verf, county verf, priv verf, and closing documentation
-Updated instruction sheet 
Let me know if you have any different recommendations for the case note header format!

1424 notes case discrepancy header update

---

actions/banked-months-updater.vbs

This fix corrects a reported issue where members without a WREG panel were getting variables carried over from previous member. Moved the variable resets outside of if statement to resolve. 
Added case note option to note no WREG panel when listing all members' WREG status in case note.

1543 Banked Months Updater bug fix for ineligible members

---

notes/vendor.vbs

When searching for a vendor, the script now goes back to the main dialog, allowing additional vendors to be searched. Also allows the script to continue correctly if timed out of maxis, and works with updated check_for_maxis for #1166

#1549 NOTES - Vendor fixing dialog looping

---

notes/smrt.vbs

Fixed typo where write_value_and_transmit was writing to wrong location on STAT/MEMB which resulted in the wrong age (the next HH member's) being written to CASE/NOTE.

#1561 Fix typo in write_value_and_transmit on STAT/MEMB

---

COMPLETE LIST OF SCRIPTS.vbs
notes/main-menu.vbs

Removed LTC button from Notes Main Menu
Updated ChangeLog to notify users of this change.
No action required for CLOS or ? for sharepoint documents.
Did not rename, left LTC in the naming for now.

1446 remove ltc button from notes main menu and include LTC scripts in alpha categories

---

actions/ma-epd-ei-fiat.vbs

Changed the script to say Unemployment income instead of UNEA.
Changed the text field length so that it shows the full statement "The script found the following unemployment income:" Previously only showed "The script found the following"

#1540 fix wording and allow full sentence to display.

---

notes/interview.vbs

We want to make sure someone hasn't navigated out of MAXIS before running the next part of the script. 
NOTE: there is only 1 call after the large series of dialogs that happens for the main dialog AND for the verbal review of required interview information. 
ALSO NOTE: there is not one after the check eDRS because eDRS does not appear to be in MAXIS and I want the dialog to stop at this screen

#1168 NOTES - Interview add check_for_MAXIS

---

actions/ma-fiater-for-grh-msa.vbs

This area of the script loops through the budgets of 6 months that were already marked, it assumes there are always 6 months to review but if there are fewer than 6, the script errors when it reads information that should be a date and is not a date. It also transmits too far if the moving is not conditional as well. 
This resolves team email from TE on 1/4/24. 
I have selected everyone for review, but I just need a couple people to give it a try. The case in the team email can be put through background and this script tested without long term impact on the case.

#1624 ACTIONS - MA FIATer for MSA GRH - bug when reading date

---

Test scripts/Casey/current-version-snap-waived-interview.vbs
notes/snap-waived-interview.vbs

Added functionality to read the CASE/NOTE from the SNAP Waived interview script run to pull the details back into a dialog so that we can complete the contact details when we do get a hold of the resident (on a future call or return call from the resident).

#1622 Add Return Contact to SNAP Waived Interview

---

notes/application-received.vbs

Added a 'replace' to remove any apostrophe in the case name and replace with a dash. This is required for the entry into SQL to save pending case information and potential expedited information for assignments. 
SQL does not allow for single quotes/apostrophes in the strings.

#1633 NOTES - App Received - replace single quote for SQL

---

notes/health-care-evaluation.vbs

Error had been reported with a cdate error. I believe this is due to handling around the baseline date, particularly needing dialog handling to ensure this is actually a date if it isn't blank. 
Also found an issue with the application date variable.
I selected everyone for review but I think having 2 reviews of the pull would be sufficient.

#1643 NOTES - HC Eval - BUG in baseline date if not a date

---

MASTER FUNCTIONS LIBRARY.vbs
dail/cola-review-and-approve.vbs

Created new function to record usage information outside of the script_end_procedure so that we can record more specific script functionality usage. 
This is an initial phase of this work and we will need to consider how we use the table columns that currently exist.
We might need to change the naming parameters when saving a part of a script run, like add 'FUNCTIONALITY - ' to the beginning or something - or maybe remove the '.vbs' and add something else. 
I also have some questions about resetting the timer. We want to be careful we are not double counting script run time. Currently I have a boolean parameter that will allow us to control resetting the timer.
Here is what the data looks like with my recording the usage in this way:
The last two are from the same script run.
We should …

#1650 and #1518 - New usage recording functionality

---

notes/client-contact.vbs
notes/snap-waived-interview.vbs

Added functionality to Client Contact to review for the 'Info Needed' CASE/NTOE created by SNAP Waived Interview to alert the worker to the questions that info needed has listed. This will allow Client Contact to redirect to SNAP Waived Interview to specifically support the Return Contact information needed. 
Pull request is scheduled to be merged on Tuesday mid day after the HT is released. 
Only additional update will be to CLOS with the HT date in the script array. Will wait until Tuesday to do this, and do it on this pull but if there is a merge issue, we can create a new pull for that specifically.

#1622 SNAP Waived Interview Return Contact added to Client Contact

---

utilities/va-verification-request.vbs

Email was using the client_ssn. Replaced client_ssn with vet_ssn in email to align with the name beign pulled in (vet_member) so that the SSN is correct regardless of what member is selected.

#1667 Replaced client_ssn with vet_ssn for email

---

notes/client-contact.vbs

Adding the output to the usage log when we redirect form client contact to SNAP waived interview. The entries would look something like this:

#1650 NOTES - Client Contact - record redirect to SNAP Waived Intvw in usage log

---

dail/new-hire-ndnh.vbs

Add handling to ensure that script returns to same DAIL message if user navigates to a different panel during dialog. Updated function nav_in_dail to read full DAIL message to ensure exact match is found in situations where the shortened DAIL message may have duplicates.

#1600 DAIL - New Hire NDNH, ensure script returns to DAIL message

---

notes/proof-of-relationship.vbs

Fix issue where script only displays selected HH members in relationship dialog, rather than displaying all relationship connections between all HH members for the selected HH members. Also fixed the functionality to add a new relationship row. However, this seems to cause issues when the dialog gets too large as the Docs Received field starts to default with info - seems to pull in the "MEMB" checkbox.

1636 notes proof of relationship resolve hh memb issues

---

notes/snap-waived-interview.vbs

This is to resolve a bug that intermittently creates a type mismatch error for certain users when pressing the no contact made button on the information needed dialog.

#1744 Waived Interview no contact 

---

utilities/elig-results-to-word.vbs

New script to create a word document of a single Eligibility Result for any program other than HC. This is supportive of processes such as appeals, overpayments or other claims activities.
I will update CLoS in another pull since this branch is quite old.

#907 New Scripts - UTILITIES - Elig Results to Word

---

notes/subsequent-application.vbs

The Subsequent Application script process still had the transfer suggestion functionality.
We will default this script to not transfer but at this time, we will allow for transfer to be manually initiated by the worker.

#1737 NOTES - Subsequent App - Remove Transfer Autofill

---

notes/hrf.vbs

Creates a line in the CASE/NOTE to indicate that a HRF for a future month is not received when running the script for a HRF for the current month.

#1634 NOTES - HRF - add option for future HRF not received

---

admin/expedited-determination-report.vbs

The Expedited Determination Report has previously used and supported by OS staff but this process ended in Jan. There was significant clean up of the data and Excel files needed. 
I have updated the script to ensure only BZST can run it and also allows the script to limit the run time. 
Currently the output to the Expedited Spot Checks is turned off until additional details can be reviewed.

#1770 Expedited Determination Report - Restrict to BZST and Update Interface

---

COMPLETE LIST OF SCRIPTS.vbs
deu/deu-main-menu.vbs
managed-care/mc-main-menu.vbs

Reset dialog1 outside of declare_main_menu_dialog function call which may help to reduce dialog errors that pop up with Managed Care and DEU main menu scripts. Activated the links to script instructions for DEU scripts and updated SharePoint links to fix broken links.

1663 Reported issues with accessing the mhc and deu menu

---

deu/ievc-list.vbs
deu/intr-list.vbs

Updated CLOS with updated script names but did not change actual script file names. Did this to ensure that DEU main menu links to correct instructions for IEVC and INTR list scripts.

#1663 Change script file names and script name within script to align with CLOS

---

admin/training-case-creator.vbs
notes/health-care-evaluation.vbs

Updates NOTES - HC evaluation to read the new locations on STAT/REVW HC popup and check STAT/HCMI for potential errors.
Updates wording in dialogs to guide HSRs with coding of review/HCMI.
Also fixes ADMIN - Training case creator to write into new field locations.
Changes drop-down options and noting for reasons a case will fail phase 1. This is a partial solution while full support of asset policy is created.

#1776 Changes to ex-parte Y/N field on stat/revw and HCMI

---

notes/returned-mail.vbs

Updated returned mail to reflect findings from FNS audit to properly act on mail returned as undeliverable (mail returned without forwarding address). Per FNS audit: when the county receives returned mail without a forwarding address for simplified reporting households, the county should hold that information and follow-up at the next scheduled certification action or periodic report about the potential change in residence. If mail returned without a forwarding address, then script will determine if case is an active, SNAP-only, 6-month reporting and if so, it will CASE/NOTE that worker should follow up on address change at renewal/recertification and not take negative action.
Will update script instructions once finalized.

1789 notes returned mail, update to reflect unclear info

---

notes/disaster-food-replacement.vbs

Updated to ensure script captures all required details from 02/2024 POLI/TEMP for TE02.11.18 FOOD DESTROYED IN A MISFORTUNE OR DISASTER. Added TIKL functionality for DHS-1609. Updated dialog and validation. Added closing issue documentation and initial county and case number dialogs.

1796 notes disaster food replacement, update to reflect new poli/temp guidance

---

notes/client-contact.vbs

Fixes issue 1816, gets the case out of wherever it may be before starting a new case note.

#1816 Client contact NAV error if in a case note

---

notes/snap-waived-interview.vbs

Corrects an issue with a blank interview date in the dialog causing string error. If the user removes it from the dialog and PROG does not have an interview date, will now enter today's date automatically.

#1744 Fixes date variable to ensure it writes to PROG

---

MASTER FUNCTIONS LIBRARY.vbs

Issue with recent update to Access_Addder "WRITE" portion. I had adjusted the script to use resi_street_full and mail_steet_full when writing however this didn't handle for the fact that dialogs sometimes have 1 or 2 fields to capture the street address. 
Updated handling to handle for both scenarios. Extra testing on this would be appreciated :). Return Mail and LTC 5181. Use had reported issue with 5181 not writing correct street address which is brought this to our attention.

#1813 Updated ADDR WRITE FUNCT- to handle for either 1 or 2 street address fields in a dialog

---

actions/transfer-case.vbs

Removed excluded time = yes req for active GRH in error handling in response to JD's email. 
Script will still default exclude time to Yes if GRH = active/app open however it will allow the user to change it to NO for circumstances that are not excluded time such as community settings.

#1844 Removed excluded time req for GRH in error handling

---

MASTER FUNCTIONS LIBRARY.vbs
notes/approved-programs.vbs

Updated Approved Programs to always redirect to Eligibility Summary
Func Lib changes are because the ASCII art in Approved Progs has  | - which is used as a delimiter and it is making all of the changlog messages show up.

#1194 Approved Programs always Redirects to Elig Summ

---

notes/eligibility-summary.vbs

These updates for strengthen the functionality and handling of Eligibility Summary.
- Only make sure that we are entering the right case notes for cash cases, there have been instances of case notes that are in disagreement or duplicate notes.
- Add family wage level amount to the cash deny note.
- Better phrasing the cash withdraws when processed with PACT. 
- Read verifs from STAT to autofill information for Cash Deny
- Keep from duplicating WCOM lines. 
Next update will include additional edit boxes to explain case actions (FIAT, Proration, MFIP Vendor)

#123 NOTES - Elig Summ - a number of enhancements and handling for specific situations

---

notes/health-care-evaluation.vbs

To support the HC PHE unwind, we were identifying cases that met standard policy by adding a CASE/NOTE. 
Now all cases should have standard policy applied and we no longer need to identify when that occured.

#1792 NOTES - HC Eval - Remove handling for NOTE about return to standard Policy

---

notes/eligibility-summary.vbs

The Elig Summ updates here are for:
1. Formatting of MFIP Special Diet NOTE - there are some oddities with diet overlap vs diet information that does not fit on the panel. 
2. There is a missing field for Medicare Savings Programs for verifications failed date and explanation.
There will be an additional pull for supporting MFIP Special Diets for multiple members on a single case but I want to get these out here quickly

#1923 & #1924 Elig Summ - overlap/missing diets verbiage & msp verifs fail

---

notes/documents-received-testing.vbs
notes/documents-received.vbs

Pull request supports #425 #1298 #999 #305 #80 #79 #78 #77 #67 
Consolidating docs received into one script and adding additional forms. Instructions: https://hennepin.sharepoint.com/:w:/r/teams/hs-economic-supports-hub/BlueZone_Script_Instructions/NOTES/NOTES%20-%20DOCUMENTS%20RECEIVED.docx?d=w1dce0cc33ca541f68855f406a63ab02b&csf=1&web=1&e=pt6bYj
Forms Supported
-Asset Form: Reads ACCT, SECU, CARS for footer month. Ability to update ACCT, SECU, CARS panels by desired month, separate dialog to captures DHS 6054 form details, and case notes.
-ATR: Captures details in dialog and case notes under its own header
-AREP: Reads AREP panel if exists and prefills dialog, updates AREP panel if arep_update checkbox is checked, case notes under its own header
-Change: Captures details in dialog and …

425 documents received updated dashboard feel and new forms

---

actions/ma-epd-ei-fiat.vbs

The search process looks only for a number so it was falsely identifying the row a non-01 member was in. 
Added additional characters to the search for it to find the person on ELIG/HC

#1928 ACTIONS - MA EPD EI FIAT - Search for MEMB better

---

notes/ebt-benefits-stolen.vbs

Updated denial reasons to reflect updates to TE02.11.126 - see below:
- State funded cash assistance, including state funded housing grants, are not eligible for EBT replacement.
- MSA, GA, and GRH benefits are not eligible for EBT replacement.
- State funded SNAP, including state funded MFIP food portions, are not eligible for EBT replacement.

#1473 NOTES - EBT Stolen Benefits, update denial reasons

---

notes/caf.vbs

In the instance that a program was not originally selected, the interview date from the Interview script run was getting 'forgotten'.
This 'remembers' the date.

#1946 NOTES - CAF - interview date from script run bug

---

admin/dail-fmed-deduction.vbs

Added exit condition if "NO MESSAGES" error appears after deleting a DAIL, which can cause an error where the script gets stuck at SELF.

#1974 ADMIN - DAIL FMED DEDUCTION, improve handling for DAIL to prevent error at SELF 

---

admin/on-demand-dashboard.vbs

When information is entered into SQL from the Dashboard - there is only one field were workers enter text free form - the tracking notes. Other string SQL fields are managed by text hard coded in the script. 
Testing ability is limited for this script as it functions on live cases from the On Demand list. No syntax errors were found. JH is scheduled for On Demand this week, I have sent her an email of the changes and to let us know any issues that arise this week.

#1967 ADMIN - On Demand Dashboard - remove single quote from strings

---

notes/caf.vbs

Updated script so that it will proceed even if EMER interview date is missing as long as there are other pending programs.

#1938 NOTES - CAF, allow script to proceed even if EMER interview date is missing

---

notes/eligibility-summary.vbs

Updates:
- Read Military Service field in STAT and add to logic for WREG 30/09 Reviews
- Include an EditBox in MFIP Ineligible processing to address SNAP assessment
- Include the ability to add energy account number for vendor 44
- Add a QCR for UHFS Shelter Expense issue
- Add QCR for MSA UNEA 44 and Shelter Needy
Most of these updates will happen in the background and workers will not notice the differences. Additional functionality to assess the QCR reports.

#1901, #43, #1942, #1971 & #1937 - LID Updates in Eligibility Summary

---

MASTER FUNCTIONS LIBRARY.vbs

Add additional error handling to capture more details in script lowdown such as the panel where the error occurs and capturing the MAXIS mode, even if not on CASE/NOTE

#1998 function start_a_blank_CASE_NOTE() - improve error handling 

---

notes/eligibility-summary.vbs

Bug fix for HC cases when the Asset window tries to open but the HH Count has not been completed. We don't need to open this pop-up anyway.

#2024 NOTES - Elig Summ - don't open useless pop-ups

---

admin/dail-decimator.vbs

Added functionality to delete both SDNH and NDNH HIRE messages that are over 12 months old from the current month. I did not run the script on these x numbers so they would be good options for testing: EX3, EX4, and EX5. Otherwise, I ran it on all other x numbers.

#2036 ADMIN - DAIL DECIMATOR, add functionality to delete HIRE messages over 12 months old

---

COMPLETE LIST OF SCRIPTS.vbs
dail/dail-scrubber.vbs
dail/sdx-match.vbs

Added functionality to pull up Combined Manual, POLI/TEMP, and HSR Manual links within a dialog when a SDX Match DAIL message is encountered. The script instructions are quite basic, but I [updated them here](https://hennepin.sharepoint.com/:w:/r/teams/hs-economic-supports-hub/_layouts/15/Doc.aspx?sourcedoc=%7B7D2E3349-1333-4628-B572-754EED31AFB4%7D&file=DAIL%20-%20SDX%20MATCH.docx).

#2017 DAIL SCRUBBER - DAIL Reference Script, handling for SDX MATCH 

---

MASTER FUNCTIONS LIBRARY.vbs

Add functionality to start_a_blank_case_note to check if already on new or existing case note. If already on case note then it PF3s and then PF9s to open a blank case note. User had reported issues with scripts not correctly creating a case note when they were already in a case note.

#2064 function start_a_blank_case_note - Check if case note already open and open a new case note if needed

---

MASTER FUNCTIONS LIBRARY.vbs

Reverts Hennepin-County/MAXIS-scripts#2065
Discovered issue with change for scripts that write multiple pieces of information to an open case note

Revert "#2064 function start_a_blank_case_note - Check if case note already open and open a new case note if needed"

---

notes/eligibility-summary.vbs

Update to Eligibility Summary to ensure it will work well with the updates to start_a_blank_case_note. 
When a CASE/NOTE is created and all information is entered, we need to back out by pressing PF3 before continuing the script.

#2064 NOTES - Elig Summ - Back out of all Case Notes after completed

---

notes/eligibility-summary.vbs

Fix of spenddown details. Some of the different types of obligations were getting mixed up. The details were displaying weirdly in the dialog and in the CASE/NOTE. Reported by a user that the amounts were incorrectly. 
Variable management completed so the correct spenddown details now display.

#2077 - Elig Summ - spenddown information output bug

---

MASTER FUNCTIONS LIBRARY.vbs

Updated actionable_dail function to include new PEPR message related to CEC Annual Info Message: "MEMBER IS CHILD UNDER AGE 6. ANNUAL HC NOTICE SENT." Message will be deleted as part of DAIL decimator runs since this message will be indicated as not actionable (actionable_dail = false).

#2093 Add new CEC message to actionable_dail function

---

deu/match-cleared.vbs

Added a dialog to capture claim numbers for CC - this should allow the script to enter  resolution_status, claim number(s), and eliminate dail message (I believe this happens automatically when the match is cleared) 
DEU team is in the middle of clearing the new quarter’s matches so they can test it for us.

#2038 Add claim number capture to DEU - Match Cleared 

---

shelter/shelter-main-menu.vbs

No error reported on this menu yet but the other menus with this declaration missing all failed at some point. 
No other menus appear to be missing a declaration of some kind.

#2084 Shelter Main Menu - declare dialog variable

---

notes/eligibility-summary.vbs

We can ignore the supportive housing disregard logic for GRH cases that are ineligible for reasons OTHER than income because the budget shouldn't matter in these instances.

#1952 NOTES - ELIG SUMM - GRH Inelig NOT Income based supp hsg logic

---

dail/catch-all.vbs

Made updates to general script functionality:
- Updated the header of the CASE/NOTE to include more specifics.
- Removed ‘Action Taken On: date & time’ from CASE/NOTE.
- Write the entire DAIL message to the CASE/NOTE.
- Updated script instructions
Added handling for the following messages:
VERIFICATIONS REQUESTED FOR THIS CASE. PLEASE REVIEW CASE (TIKL)
- Script navigates to CASE/NOTEs to find matching CASE/NOTE (>>>VERIFICATIONS REQUESTED<<<) with Verifs due date that matches the TIKL date. Opens dialog where worker can either: indicates that verifications have been received and the script will then delete the TIKL and then redirect to NOTES - DOCS RECEIVED, OR indicate that verifications have not been received and the script will then run the case through background and then end.
DISA …

1226 DAIL - CATCH ALL, evaluation and updates

---

MASTER FUNCTIONS LIBRARY.vbs

Created function read_program_history_case_curr. The function navigates to Program History from CASE/CURR and reads all of the program history. It also creates an array of all active programs. In terms of the function parameters:
- PROGRAM_ever_active: TRUE or FALSE indicating whether program was ever active (CASH, MSA, FS, MA, EMER, GRH, GA, MFIP, DWP, QMB, SLMB, CCAP, QI1, RCA, IV-E, IMD)
- PROGRAM_currently_active: TRUE or FALSE indicating whether program is currently active
- PROGRAM_date_closed: Most recent date of closure (Eff/Inact Date) for program
- PROGRAM_reason_closed: Reason for most recent closure of program
- active_spans_array: Creates an array of all currently active programs - program name, APPL date, Eff/Inact Date
There were a number of programs listed from 10-20 years …

#1724 Create function to read program history

---

MASTER FUNCTIONS LIBRARY.vbs

Updated language in actionable_dail function to reflect correct DAIL language for CEC PEPR message - "MEMBER IS CHILD UNDER AGE 6 - ANNUAL HC NOTICE SENT". Fixes https://github.com/Hennepin-County/MAXIS-scripts/issues/2093.

#2170 Update language to match actual PEPR DAIL message

---

admin/on-demand-dashboard.vbs

Since the interview waiver is no longer in effect, On Demand handling no longer needs to allow for interview dates to be mismatched. Removing the delay in review of mismatched interview dates.
Waited until cases could be unwound before completing this update.

#2157 ADMIN - On Demand Dashboard - remove interview waiver handling

---

COMPLETE LIST OF SCRIPTS.vbs
dail/MEC2-message.vbs
dail/dail-scrubber.vbs

Added functionality to DAIL scrubber to determine if MEC2 message is actionable or non-actionable. For non-actionable messages, the script will notify the worker before deleting the message. The script has handling to navigate back to the DAIL message if needed to delete the message. If the MEC2 message is actionable, then the script will navigate to the corresponding STAT panel and provide a link to the HSR manual for further guidance on how to process the message.

#99 Create DAIL scrubber for MEC2 messages

---

notes/eligibility-summary.vbs

Ignore supportive housing disregard in any month with no counted income. This will handle for any initial month in which the income is unavailable and not counted. Additionally added handling to note information when all of the income is disregarded.

#1952 NOTES - Eligibility Summary - GRH Initial App Month Handling

---

MASTER FUNCTIONS LIBRARY.vbs
misc/interview-forms-classes.vbs
notes/interview.vbs

Updates to the interview script to better support forms, interview policy and handling. 
- Verifications can be entirely cleared. 
- Improve the 'Clear' button for all question based verifications.
- Updated the verbiage in the dialogs and outputs to align with the the allowance for different form selections.
- Expedited Determination output in the WIF needed better logic to handle for cases that do not require an expedited determination and for the output when used by the interview team.
- Removed signature date. 
- Updated handling for verbal signature documentation.
- Default second signature to Not Required for a single person household.
This update does not handle for two additional planned updates:
1. Add Program History information to Follow Up (maybe XML output). 
2. Update the …

#2050, #2158 & #2178 NOTES - Interview Updates to enhance user experience

---

notes/hrf.vbs

Updated error handling for JOBS and UNEA panels:
- Fixed error where JOBS error handling was updating UNEA error message instead of JOBS error message
- Fixed handling for both JOBS and UNEA panels where blank fields are replaced with "0.00" so that it can properly match across prospective, retrospective, and SNAP PIC fields
- Added improved handling for JOBS with income end dates. Script will check if the end date is from a previous month, if so then retrospective, prospective, and SNAP PIC all need to be set to 0.00 or blank. If the JOBS income end date is the first of the month and it matches the footer month, then the panel will be evaluated to make sure that retrospective, prospective, and SNAP PIC are all the same amount.

#2189 NOTES - HRF, jobs and unea panel reading error handling

---

admin/dail-unclear-information.vbs

Ensure ELIG/FS is viewed for current month rather than defaulting to the footer month for the first DAIL message encountered for a case.

#671 #2208 DAIL - UNCLEAR INFO, Ensure ELIG/FS viewed for CM, add changelog

---

misc/interview-forms-classes.vbs

Worker reported issue with PDF generated as part of interview script that cut off worker entered comments regarding JOBS panel. Added handling to adjust cell height based on length of worker comments

#2236 MISC - INTERVIEW FORMS CLASSES, Adjust cell height based on length of worker comments

---

notes/caf.vbs

Add handling to ensure that script creates a new Verifications Requested CASE/NOTE when new verifications are added to the Verifs Needed field in the dialog. If no new verifications are added, then the script will not create a new CASE/NOTE.

#2224 NOTES - CAF, Improve handling for reading/adding Verifs CASE/NOTEs

---

admin/interview-team-case-tracking.vbs
admin/interview-team-cases-worklist.vbs
notes/interview.vbs

Update to Interview - added the XML creation at the beginning to prevent losing cases. 
*Testing is hard because developer mode turns off the XMLs. Developer mode is triggered by being in TRAINING. If you turn it 
off, make sure to delete your XMLs AND the PDFs of the interview notes. I ran through tests in training on this. 
Interview Worklist - now adds cases directly to the spreadsheets the  processors use
** I have run this worklist successfully and will be directly supporting the few workers who will run it daily next week to ensure no bugs. 
Interview Tracking is just here to stay connected - it is not ready for release and I am the only user of this script. 
If I can get reviews on this, I will pull in on Monday morning and be ready for any unforeseen bugs.

#2233 & #2235 - Interview Team supports

---

notes/interview.vbs

The main dialog kept appearing when the incomplete option was pressed. Plus there were two confirmations before leaving the loop. 
Worker reported this prevented them form using the incomplete functionality.

#2254 NOTES - Interview - dim the variable to leave the loop

---

deu/paris-match-cleared.vbs

Request from worker to include the full resolution status in the CASE/NOTE header rather than the abbreviation for clearer communication purposes to other teams. Updated the script to show the full resolution status in the CASE/NOTE header.

#2267 DEU - PARIS MATCH CLEARED, show full resolution status in CASE/NOTE header

---

notes/interview.vbs

Since I cannot turn off my MEMO access, I cannot test that option. However, this worker is on the interview line and should be able to check it pretty quickly once in place. As far as we are aware this is only impacting one person.
I did test that the MEMO still sends since I do have access.

#2274 NOTES - Interview - skip MEMO if not opened

---

notes/interview.vbs

There's a bug in the expedited information because I used the wrong conditional to make sure the expedited assessment happened at the right time.

#2279 NOTES - Interview - BUG in getting Exp Det accurate

---

actions/earned-income-budgeting.vbs

Attempt 2 to make the dialog sizing work properly. It should work and resize now regardless of the number of checks and programs selected, but definitely worth double-checking.

#2278 ACTIONS - EIB, Fix dialog sizing, add changelog

---

misc/interview-forms-classes.vbs

Updated the logic in the forms class to:
- Correctly identify if the questions is 'entirely blank'
- Ensure entry of details for shel-hest question types
This should resolve missing detail from the error report.

#2295 MISC - Interview Forms - fix logic for CASE/NOTE entry HUF Q7
