MASTER FUNCTIONS LIBRARY.vbs
Test scripts/Casey/WCOMs/testing_function.vbs

This function should end the script if the verbiage cannot fit in to the MEMO/WCOM.

FUNCTION write_variable_in_SPEC_MEMO - bug fix

---

MASTER FUNCTIONS LIBRARY.vbs

We have regular need to review dates to determine if they fall on days the county is open or changing dates to be when the county is open. 
is_date_holiday_or weekend
change_date_to_soonest_working_day
Created initially for appointment notices.

2 new functions to help with dates

---

Test scripts/Casey/On Demand/testing_notices.vbs
admin/bulk-applications.vbs
admin/bulk-recertifications.vbs
admin/individual-appointment-letter.vbs
admin/individual-nomi.vbs
case-assignment/ca-application-received.vbs
notes/application-received.vbs

All of the scripts that support the On Demand Waiver needed to be updated to have new verbiage and new handling for how far out the dates of appointment are.

On demand verbiage

---

MASTER FUNCTIONS LIBRARY.vbs
Test scripts/Casey/functions/testing_write_date.vbs

MAXIS gets picky when scripts try to write in spaces not meant for writing - even if they are spaces. Updated the script so that it will not try to write what is between the dates.

Update write_date function to work better

---

notices/select-wcom.vbs

Removed WCOM for 'FSET Failure to Comply' added WCOM for 'Voluntary E&T'

WCOMs for SNAP Bulletin 18-01-01

---

admin/expedited-review.vbs
admin/work-assignment-completed.vbs

@C-Love and I finally are ready to release this. Updates made to existing processes for ADMIN scripts EXPEDITED REVIEW and WORK ASSIGNMENT COMPLETED to support the QI review work. I pull thee!

#191 QI Expedited Review Work Enhancement 

---

MASTER FUNCTIONS LIBRARY.vbs
actions/abawd-fiater.vbs
notes/abawd-tracking-record.vbs
notes/abawd-waived-approval.vbs
notes/caf.vbs
notes/closed-programs.vbs
notices/snap-e-and-t-letter.vbs

Updates to scripts and functions from issue #419. Initial tested, but I'd love some fresh eyes in case I miss anything.

Snap banked months scrub

---

MASTER FUNCTIONS LIBRARY.vbs
actions/main-menu.vbs
bulk/main-menu.vbs
notes/main-menu.vbs
notices/main-menu.vbs
utilities/main-menu.vbs

This sub is a part of the COMPLETE LIST OF SCRIPTS and uses the 'in_testing', 'testing_category', and 'testing_criteria' parameters of the script list class.
This allows for all the testing.

#453 Adding the 'Show Button' sub to all menus to allow for new scripts to have testing functionality

---

dail/dail-scrubber.vbs
notes/avs.vbs

Added DAIL Scrubber to run NOTES - AVS. Updated NOTES - AVS to support reading case number and defaulting initial options based on the type of the TIKL.

Avs dail scrubber

---

admin/review-report.vbs

Updates to Review Report to alter the STATs gathering.
Also adding NOMI and APPT NOTC functionality to this script.

#440, #433, #458 ADMIN - Review Report Updates - NOMIs, STATs, and Appt NOTCs

---

actions/transfer-case.vbs
notes/csr.vbs
notes/hc-renewal.vbs
notes/health-care-transition.vbs
notes/mets-retro-health-care.vbs

Update all 5 scripts. Just want a second set of eyes on this.

Edge browser updates

---

admin/review-report.vbs

Functionality done and tested to add the CASE:NOTE for the end of the processing month when gathering these statistics.

#387 ADMIN - Review Report - REVW Closure NOTE added

---

MASTER FUNCTIONS LIBRARY.vbs
actions/job-change-reported.vbs
actions/transfer-case.vbs
admin/cs-good-cause.vbs
admin/individual-appointment-letter.vbs
admin/individual-nomi.vbs
admin/individual-recertification-notices.vbs
admin/memo-from-list.vbs
admin/unea-updater.vbs
bulk/case-transfer.vbs
dail/fmed-deduction.vbs
dail/overdue-baby.vbs
notes/application-received.vbs
notes/closed-programs.vbs
notes/health-care-transition.vbs
notes/interview-no-show.vbs
notes/significant-change.vbs
notices/12-month-contact.vbs
notices/dwp-es-referral.vbs
notices/eligibility-notifier.vbs
notices/ltc-asset-transfer.vbs
notices/method-b-wcom.vbs
notices/pa-verif-request.vbs
notices/snap-e-and-t-letter.vbs
shelter/shelter-mandatory-vendor-approved.vbs
shelter/shelter-mandatory-vendor-memo.vbs

This is all ready.
There are a number of new parameters that are available. I changed this because as we start to really use MEMOs we should incorporate different ordering and options. 
Note that updates to the On Demand process scripts are NOT included in this pull request - these have local functions that are working well there.

#107 Update function start_a_new_spec_memo - now it has ALL the parameters

---

misc/tasks-dash.vbs

this is how we might pull request

This is a test of pull requests

---

misc/new-task.vbs

Now we are working on a new script for pull requests

Another Pull request test

---

misc/hss-service-authorization-update.vbs

Added condition if HSS date is after the initial start date of the SSR agreement.

#473 - Added supports for if the agreement date is after the HSS date

---

notices/pa-verif-request.vbs

The functionality should work well here. 
I have questions about the functionality where we figure out the building of the MEMOs. 
Can we discuss?

#506 NOTICES - PA Verif add GRH Functionality

---

dail/cses-scrubber.vbs

No new functionality and we are not removing functionality. This will just allow the script to be used on cases that have Type 37 or Type 40 CSES messages without erroring.

#420 DAIL Scrubber - CSES Scrubber - Ignore Spousal Support Messages

---

notes/interview.vbs

A series of updates to Interview based on user feedback.

#62 NOTES - Interview - testing PATCH 2

---

notices/pa-verif-request.vbs

Updates to PA Verif Request.
Making sure we don't add information from INQX for a future month.
Updating the verbiage in the CASE NOTE to make it cleaner.

#550 NOTICES - PA Verif Request - formatting and handling

---

MASTER FUNCTIONS LIBRARY.vbs

Updates to the Resources Notifier function so that it updates all the places that the resources are called. 
ERR Msg handling to correctly determine if something was selected or not.
Added Shelter informaiton
Added WIC information
Ready for review and pulling in.

#557, #542 & #346 FUNCTIONS LIBRARY - Resources Notifier function update

---

admin/expedited-determination-report.vbs
notes/caf.vbs
notes/expedited-determination.vbs

Updates to 
NOTES - CAF
NOTES - Expedited Determination 
with enhancement for functionality
New script
ADMIN - Expedited Determination Report 
All to support agency wide expedited processing efforts.

#345 Expedited Determination Functionality Release

---

MASTER FUNCTIONS LIBRARY.vbs
actions/earned-income-budgeting.vbs
misc/hss-maxis-facility-report.vbs
misc/hss-service-authorization-update.vbs
notices/pa-verif-request.vbs

Removing 'sort_dates' from individual scripts and moved it to the Functions library. Then we remove it from the 4 scripts it is already locally defined in.
HSS scripts to be tested by @IlseFerris . 
Added better commenting to the function in MASTER FUNCTIONS LIBRARY

#527 - Move sort_dates function to FuncLib

---

MASTER FUNCTIONS LIBRARY.vbs
actions/pf11-actions.vbs
admin/individual-appointment-letter.vbs
admin/on-demand-waiver-applications.vbs
admin/task-based-assistor.vbs
notes/imig-status.vbs
notes/interview-no-show.vbs

change_date_to_soonest_working_date can now move forward OR back. New parameter added. Scripts that use this function also updated. 
get_program_and_case_status_from_case_curr had a bug in which it mistakes EGA for GA - fixed it with a space.

#593 & #594 MASTER FUNCTIONS LIBRARY UPDATES

---

notes/caf-testing.vbs
notes/caf.vbs

We will need to merge this in later but I need to remove the branch of the CAF script as the ADDR updates must take place tomorrow and the branch will cause a number of merge conflicts. this allows us to keep testing but prevents merge conflicts.

#539 - Adding a Testing Version of NOTES - CAF to MASTER under a different name for testing of 'save your work'

---

MASTER FUNCTIONS LIBRARY.vbs
notes/application-received.vbs
notes/caf-testing.vbs
notes/caf.vbs
notes/expedited-determination.vbs
notes/expedited-screening.vbs
notes/interview.vbs

Ready for review. @C-Love will be updated the rest of the scripts/functionality in the issue.

#553 hest standards

---

actions/pf11-actions.vbs

ACTIONS - PF11 ACTIONS has been updated to remove NSI information.

#530 pf11 update nsi removal

---

utilities/uc-verification-request.vbs

#187 utilities uc verification request

---

utilities/qi-avs-request.vbs

updated to add application date to the email information and ensure that the script is on the right screen in MAXIS.

#583 UTILITIES - QI AVS REQUEST

---

misc/hennepin-favorites.vbs
misc/tags-main-menu.vbs

Updating the menu scripts to take away the restriction to be available to testers only. 
This will allow anyone using scripts to use the new menu functionality.

#45 & #46 Releasing new Menus - Tags and Favorites - to All

---

COMPLETE LIST OF SCRIPTS.vbs
admin/dail-12-month-contact.vbs

Initial test ran today. All DAILs were captured. A couple issues with saving the file (resolved) and an issue with not having a MAXIS background check. 
User is Laurie H. Instructions updated locally for her. Script will stay in testing through 12/01/2021 (the next time the run will take place.)

#155 dail 12 month contact

---

actions/pf11-actions.vbs

As of 10/2021 all PMI merge requests need to go through SIR Webforms. Updated changelog and closing issue documentation as well.

#633 ACTIONS - PF11 ACTIONS: Remove PMI Merge functionality

---

utilities/report-to-the-bzst.vbs

This adds an attachment to the report email.

#614 - UTILITIES - Report to the BZST - Adding txt save your work file for CAF or Interview reports

---

admin/on-demand-notes.vbs

removed the email correction and updated the date handling for STAT/PROG

#189 new script on demand case notes for qi

---

COMPLETE LIST OF SCRIPTS.vbs
admin/search-case-note.vbs

New script created and ready to release to QI for initial testing.

#520 New Script - ADMIN - Search CASE NOTE

---

utilities/uc-verification-request.vbs

#644 UTILITIES - UC VERIFICATION REQUEST

---

admin/expedited-review.vbs

Added option to default to running for specialty groups only. Added function to check to see if file exists vs. erroring out or forgetting certain files to archive when running different options.
Removed DWP emails from process.

#666 ADMIN - EXPEDITED REVIEW: Added specialty only option

---

notes/documents-received.vbs

Added changelog, removed case noting and checkbox/resized dialog.
Did not complete closing project documentation as there is an issue to rebuild this in more of a dashboard process.
Updated instructions to have new MTAF information dialog though.

#694 NOTES - DOCS RECEIVED: Removed MFIP DVD option

---

admin/find-q-flow-population.vbs
notes/client-contact.vbs

Ready for review. Added EP3 and ensured that ADMIN - FIND Q FLOW POPULATION matched what's in NOTES - CLIENT CONTACT.

#733 q flow population

---

dail/cses-scrubber.vbs

Update to the DAIL Scrubber so that the extra pennies are added to the first PMI for that specific message.

#741 DAIL - CSES Scrubber - pennies to the right people

---

notes/documents-received.vbs

Interviews are not required for MTAF process - HSR manual is being updated with this clarification. Updating the script to follow this procedure.

#392 - NOTES - Docs Recvd - MTAF - Remove Interview Date

---

MASTER FUNCTIONS LIBRARY.vbs
Test scripts/Casey/Utilities/i-am-a-test.vbs
actions/job-change-reported.vbs
admin/avs-report.vbs
admin/dail-12-month-contact.vbs
admin/expedited-review.vbs
admin/mont-report.vbs
admin/on-demand-notes.vbs
admin/review-report.vbs
admin/unea-updater.vbs
bulk/find-maepd-medi-cei.vbs
nav/postponed-actions-tracking.vbs
notes/application-received.vbs
notes/interview.vbs
notes/returned-mail-received.vbs
notices/pa-verif-request.vbs

We have updated the function to read the program status and case status. This function outputs boolean parameters and string parameters with details about the case situation. 
Updates made at this point:
1. The program specific string parameters will now output 'ACTIVE', 'INACTIVE', 'PENDING', 'REIN' adding 'APP OPEN' and 'APP CLOSE'.
2. Added outputs for emergency assistance. 'emer_case', 'emer_status', 'emer_type' that outputs a boolean, status string, and which emer program.
3. Added output for 'msp_type' to output a string of the msp program for the case.
4. Added two string parameters of lists of active programs and pending programs for the case. 
This function was found in 14 scripts. 13 of them are updated on this branch. There is one script that will be updated on a different …

#716 Update Function 'determine_program_and_case_status_from_CASE_CURR' for more string 

---

actions/claim-referral-tracking.vbs

This is the update of the function call in ACTIONS - Claim Referral Tracking for issues #716
This is connected to Pull Request #765

#716 ACTIONS - Claim Referral Tracking -  update prog and case status function

---

COMPLETE LIST OF SCRIPTS.vbs
admin/track-autoclose-overpayments.vbs

We are starting with SNAP functionality. This is specific to the processing for cases that have overpayments due to the pause in the autoclose process for 02/22. 
Limited users and additional functionality/testing to continue.

#768 ADMIN - Track Autoclose Overpayment - New Script Created

---

admin/on-demand-waiver-applications.vbs

Update to the script ADMIN - On Demand Applications so that we have additional functionality. We will now review cases that closed within the past 30 days and cases that were in another county. 
We also have functionality to carry cases from the worklist in one day to the next.
No review needed but @IlseFerris and @MiKaylaH22 - FYI that this is out here and I am pulling it in tomorrow morning.

#667 - ADMIN - On Demand Applications - Next Gen Update

---

actions/full-interview.vbs
misc/complete-task.vbs
misc/tasks-dash.vbs
notes/application-check.vbs
notes/application-received.vbs
notes/interview.vbs
notices/eligibility-notifier.vbs
retired-scripts/waived-er-interview-screening.vbs
utilities/lost-applymn.vbs

UTILITIES - LOST APPLYMN name will change with the work in #628

#697 Removed APPLYMN verbiage from scripts

---

MASTER FUNCTIONS LIBRARY.vbs

This one got missed in the last update.

#674 FuncLib: provide_resources_information: update mnbenefits website

---

notes/caf.vbs
notes/expedited-determination.vbs
notes/interview.vbs

Using the now variable instead of date so that the time is included.

#786 Expedited Determination Functionality to output date and time instead of just date

---

notes/emergency.vbs

[CM reference to reivew](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=CM_00161801)
@C-Love after the review can you merge the pull request, and add the replace the file in the desert island folder? I've updated the other files today. Thank you!

#792 NOTES - EMERGENCY: Updated 2022's 200% FPG amounts

---

bulk/ltc-grh-list-generator.vbs

Details in the issue and the commits.

#804 ltc grh list generator

---

admin/work-assignment-completed.vbs

only commenting out because we don't want to lose this until we know our final process

#667 ADMIN - Work Assignment Completed - Remove Correction Emails

---

notes/appeals.vbs

updated docket number handling
removed worker signature from ind dialog
used new case-curr function
little clean up but still in scope

#770 NOTES APPEALS BUG DOCKET NUMBER  not case noting

---

dail/dail-scrubber.vbs
dail/new-hire-ndnh.vbs
dail/new-hire.vbs
dail/tpqy-response.vbs

Ready for pull request. BNDX scrubber will be pulled in at a later time.

#814 dail ievs updates

---

dail/dail-scrubber.vbs
dail/new-hire-ndnh.vbs
dail/new-hire.vbs

There was a bug in NDNH for gathering the member #/SSN if using the INFC portion of the script. Changed code to use the same code to gather this information and then go into If...statements for the specific processes (HIRE or INFC). 
Also updated BlueZone string entries to upper case, just in case.

#814 dail ievs bug fix

---

notes/caf.vbs

Pulling this in a critical with no review.

#827 NOTES - CAF - Qual Question 3 bug

---

dail/new-hire-ndnh.vbs

If the SSN is known and we are just clearing the INFC we don't need to go to STAT at all. Added functionality to support if going to stat is necessary or not.
Successfully cleared old NDNH message in INFC, and tested new NDNH message in INFC (but they won't clear due to the known MAXIS issue).

#814 DAIL - NEW HIRE NDNH: Bug for INFC portion

---

actions/transfer-case.vbs

adding a back-to-self and maxis background check to ensure transfer is complete, thinking we may need a script run lowdown in case the error is occurring at transfer

#393 ACTIONS TRANSFER CASE

---

dail/bndx-scrubber.vbs

Tested on both types of messages. We don't have any in county but I can provide a caseload out of county to test.

#814 DAIL - BNDX SCRUBBER: added handling for both SSN_present TRUE or FALSE

---

actions/transfer-case.vbs

Ensured that GRH IS ALWAYS EXCLUDED TIME CASE - ANSWER MUST BE 'Y'

#393 ACTIONS TRANFER CASE bug fix

---

utilities/uc-verification-request.vbs

Updates requested by ES Leadership for DEED request process starting Monday.

#847 uc verif request

---

utilities/uc-verification-request.vbs

Made updates suggested from original pull request: updated dialog and added msgboxing for training region.

847 pull request updates

---

MASTER FUNCTIONS LIBRARY.vbs

Added descriptors, tested for issues and checked for duplicate variables. No issues.
Once this is approved I'll create a new branch to update the scripts that hold these functions.

#839 MASTER FUNCTIONS LIBRARY: added view_poli_temp function

---

dail/dail-scrubber.vbs
dail/tpqy-response.vbs

Added supports for SVES Covered Quarters Messages.

816 sves covered quarters

---

actions/transfer-case.vbs
notes/caf.vbs
notes/expedited-determination.vbs
notes/interview.vbs

Removed local function VIEW_POLI_TEMP as this is now in the FuncLib. @C-Love is updating NOTES - RETURNED MAIL RECEIVED in another branch.

839 view poli temp script updates

---

COMPLETE LIST OF SCRIPTS.vbs
admin/find-hidden-excel.vbs

New script to find invisible Excel Files because scripts be opening Excel files with invisible status.

#780 NEW SCRIPT - ADMIN - Find Hidden Excel

---

actions/transfer-case.vbs

Error reported: "CURRENT FIN RESP CO MUST BE BLANK IF EXCLUDED TIME CASE (Y/N) IS N"
blanked out all of the fields if excluded time is no

#393 ACTIONS - TRANSFER CASE - bug fix

---

deu/bulk-match-cleared.vbs

the spreadsheet sometimes formats the income amount to remove the . and the 00 but it is not consistent.
Used the left 4 of the amount to confirm we have the right match the report (excel) comes from REPT/IEVC which makes me confident this is sufficient
example
2150.50
excel income 
2150.5

#498 BULK - DEU-MATCH CLEARED - bug reported

---

dail/ltc-remedial-care.vbs

Updated Remedial care amounts for July 2022. Unable to fully test due to lack of remedial care messages currently

873 dail remedial care updates

---

deu/paris-match-cleared.vbs

See commits - 1st for no SSN supports. 2nd for critical fixes/updates. 3rd for Closing issue documentation. 
I did not clear any messages, but I got the script to work all the way through to just before updating and the case note. Let's get some DEU folks lined up right away in the AM to test this.

880 paris dail bug

---

MASTER FUNCTIONS LIBRARY.vbs

Update based on DHS/MN.IT "known issue" when entering lower case strings into BlueZone vs. upper case.

#866 FuncLib: Updated navigation strings to UpperCase

---

deu/bulk-match-cleared.vbs

#498 BULK - DEU-MATCH CLEARED

---

COMPLETE LIST OF SCRIPTS.vbs
MASTER FUNCTIONS LIBRARY.vbs
misc/elig-main-menu.vbs
notes/approved-programs.vbs
notes/closed-programs.vbs
notes/denied-programs.vbs

Adding the script to Complete list of scripts.
Ensure the name is displayed correctly.
Redirect from Approved, Closed, Denied Programs.

#123 - Eligibility Summary - Adding the script to testing availability

---

admin/bulk-inactive-transfer.vbs

added priv handling, the ability to restart, closing documentation, and error messaging
this would be better as an array but for now I left it as is
tested and it works

#868 BULK - INACTIVE TRANSFER

---

admin/dail-12-month-contact.vbs

MAXIS Background check was in a spot that was causing issues with the PRIV handling. Tested with rest of 07/22 list, and is working as intended.

#891 ADMIN - 12 MONTH CONTACT: Fixed bug w/ Priv cases

---

nav/nav-poli-temp.vbs

Added the set cursor for only the TABLE option as that's the only option that requires it. Did not change log since this is such a small change.

#886 NAV - POLI TEMP: fixed bug for EMSetCursor for INDEX option

---

notes/client-contact.vbs

Did not add changelog intentionally due to it being a single case load.
Removed commented out baskets,
Added newly added closing project documentation item.

#624 NOTES - CLIENT CONTACT: added last DWP basket

---

actions/earned-income-budgeting.vbs

dialog err msg handling to ensure that any check entered has a date, amount and hours

#916 - ACTIONS - Earned Income Budgeting - make sure paycheck info is complete

---

deu/bulk-match-cleared.vbs
deu/match-cleared.vbs

921-Problem: HC matches that have FS programs are coming up on STAT/MISC report
Resolution: remove STAT/MISC handling for all HC matches on BULK list
922-Problem: error on IULB "enter comments to explain actions taken"
Resolution: evaluate do loop on IULB to ensure match is cleared before case noting
Findings: "BO-Other" was commented out as the HC cases were not to be cleared BO during he pandemic. The pandemic is not ending until Oct currently so we will add handing to ensure HC cases are not cleared "BO".
The Supervisor has decided to allow the workers to select BO for HC and the terminology on IULB will be No review due during the match period.

DEU - match cleared & bulk match cleared #921 & #922

---

notes/application-received.vbs

add info to Email for Request to APPL process: A SPEC/MEMO has been created. If the client has completed the interview, please cancel the notice and update STAT/PROG with the interview information. Case Assignment is not tasked with cancelling or preventing this notice from being generated.

887 NOTES - APPLICATION RECEIVED

---

admin/dail-fmed-deduction.vbs

Instructions in this folder: T:\Eligibility Support\Mnsure\SSR Folder\SHELTER PROJECT\REPORTS Instructions\Laurie H Directions for Running Reports
Tested for 08/2022 PEPR messages without issues.

914 bulk fmed messages

---

admin/review-report.vbs

Reformat of MEMO for long list of programs. One character change

#942 - ADMIN - Review Report - Bug with long programs list - MEMO too big

---

admin/expedited-determination-report.vbs

Script will create emails and NOT send yer and update the reports.

#940 ADMIN - Exp Det Report - worker data incorporated

---

admin/mont-report.vbs
admin/on-demand-waiver-applications.vbs
admin/review-report.vbs

Since this was a very targeted update, I did not add closing project documentation at this time.

946 qi hss updates

---

dail/dail-scrubber.vbs
dail/mfip-orientation-dail.vbs
notes/interview.vbs
notes/mfip-orientation.vbs

2 new scripts 
NOTES - MFIP Orientation
DAIL - MFIP Orientation
Update to DAIL Scrubber to access the new script.
Includes comments added to NOTES - Interview. 
Another pull will be needed for:
- Update Complete List of Scripts
- Update NOTES ChangeLog
- Update FuncLib Changelog
- retire DAIL - Financial Orientation Missing

#800 - Add MFIP Orientation to stand alone script and DAIL functionality

---

admin/basket-review.vbs
admin/on-demand-waiver-applications.vbs
admin/vendor-list.vbs
deu/rept-ievc-list.vbs
managed-care/mc-enrollment-note.vbs

Remove mention of VGO/ESSO from scripts:
admin/on-demand-waiver-applications.vbs-removed todo 
deu/rept-ievc-list.vbs - remove
admin/vendor-list.vbs - remove, added changelog block 
admin/basket-review.vbs - removed todo
mc-enrollement-note.vbs - line 436 commented code

#257 Remove mention of VGO/ESSO from scripts

---

notes/imig-ema.vbs

#944 NOTES - IMIG - EMA - add TIKL

---

utilities/copy-panels-to-word.vbs

Script is updated to support the output of PIC and Income Calculation information from STAT panels. 
Created a function to correctly format the document - adding page breaks where they are needed

#735 & #969 - UTILITIES - Copy Panels to Word - Output PIC and add a function for insert page break

---

utilities/request-access-to-priv-case.vbs

#941 UTILITIES - Request Access to PRIV Case - Update dialog

---

notes/caf.vbs
notes/expedited-determination.vbs
notes/interview.vbs

NOTES - Interview
NOTES - CAF
NOTES - Expedited Determination

#845 Update to NOTE for Exp Det Information to better define screening vs determination

---

admin/cola-decimator.vbs

I'm literally the only user of this script, so little impact if issues occur.

976 mass change updates

---

admin/on-demand-waiver-applications.vbs

This is functionality only to change the initial data pull to getting information from a SQL table with MAXIS data from the InfoStore. 
This change does NOT alter the experience of QI processing this worklist. The working excel and worklist are still managed in Excel.

#667 - Move On Demand Applications to using SQL instead of BOBI

---

notes/emergency.vbs

This is a quick fix with just a single character and a changelog. Full project documentation and such not completed as this is the quickest of fixes.

#990 NOTES - Emergency - EGA screening bug when amounts are equal

---

admin/work-assignment-from-excel.vbs

Adding the option to send an email of the assignments when completed. 
Additionally adds an option for selecting from QI members in a checkbox.

#703 ADMIN - Work Assignment from Excel

---

admin/mont-report.vbs
admin/review-report.vbs

Some updates to make restarts possible and me sure we don't pull data from the wrong place in REVW.

#949 & #996 ADMIN - MONT and Review Report - restart stats - stats looks weird in REVW

---

notes/client-contact.vbs

Changed suggested population to N/A vs. no suggestions available Added changelog
Updated closing project documentation

#985 NOTES - CLIENT CONTACT: Removed adults/families from Q-flow

---

notes/application-check.vbs

If case is in a basket where the PND2 display limmit has been reached the script is stuck in a LOOP.

#1018 - NOTES - Application Checkk - bug when PND2 display limit is reached

---

notes/interview.vbs

This is a change to the messaging in the script to the user only, no functionality change. 
Messages that have been updated:

#904 NOTES - Interview - Agency Signature not needed

---

admin/wf1-case-status.vbs

Big time updates to support person based SNAP statuses, and searching for more than one member, etc.

1024 wf1 case status updates

---

MASTER FUNCTIONS LIBRARY.vbs

Verification of dates found at: https://hennepin.sharepoint.com/teams/ga-connect/OBFDocuments/Forms/AllItems.aspx?id=%2Fteams%2Fga%2Dconnect%2FOBFDocuments%2F2023%20Payroll%20Calendar%2Epdf&parent=%2Fteams%2Fga%2Dconnect%2FOBFDocuments

#1031 Updated holidays_array with 2023 holiday dates

---

notes/interview.vbs

This did NOT actually get pulled in.

#1038 NOTES - Interview - SNAP change Reporting  - income threshold to 125

---

notes/imig-sponsor-income.vbs
notes/imig-status.vbs

Both issue #89 and #1045 are in this pull request. 
Will update COMPLETE LIST OF SCRIPTS directly to change the NOTES - IMIG - STATUS text from all caps.

89 notes imig spon

---

misc/log-hours-and-activity.vbs
misc/view-hours-and-activity.vbs

Updates in this pull:
- Commented out the 'Leave Request' functionality. We are dropping that for now but might resume it in the future.
- Moved to having one Time Tracking Per Person - no longer by year
- Dynamic creation of the list of weeks, pay periods, and months
- Using an 'Active Time Period' for lookback for speed and ease of use. 
- Automatic archiving by year done by the script.

#622 BZST Time Tracking Initial Functionality Complete

---

deu/bulk-match-cleared.vbs

Removed worker_county_code
Removed MH as authorized script user
Updated removed 2 if statements and made 1 if statement for adding information to an array. Removed excess excel_row counts that was causing cases to be skipped. Added entry record 0 script end per issue request. Updated msgbox to user at excel output to have more information. Reviewed closing issue documentation

#983 DEU - BULK MATCH CLEARED: Fixed bug with incrementing excel row

---

CLOSING ISSUE DOCUMENTATION.vbs
COMPLETE LIST OF SCRIPTS.vbs
utilities/all-scripts.vbs

This update preps the structure to have the policy references added. We will need to decide on a course of action for filling in the details of these references.

#841 Adding a list of Policy References for the script to the Complete List of Scripts

---

MASTER FUNCTIONS LIBRARY.vbs

See POLI TEMP 19.132 for dates

#1068 FuncLib: Updated ten-day cutoff dates for 2023

---

dail/dail-scrubber.vbs

Updates to the DAIL scrubber that will:
- Allow the script to find the correct message better - this is a new function that can be added to any DAIL scrubber script.
- Determine if the script is being run in inquiry. Each functionality can be evaluated to determine if the script should stop when run in INQUIRY.

#1067 & #476 DAIL Scrubber Navigation

---

notes/caf.vbs

Need to read the interview dates in a program specific way.

#623 NOTES - CAF - bug fix to the interview date required functionality

---

dail/dail-scrubber.vbs

Reviewed the DAIL Scrubber individual functionality and added a script end procedure for the scripts that require the ability to take action.
The script end procedures are all in the main DIAL Scrubber.

#476 DAIL Scrubber - script end if in inquiry sometimes

---

CLOSING ISSUE DOCUMENTATION.vbs

Also added a date to see if we have the most up-to-date version when reviewing code, and updated the MAXIS entry line to fit in line with all other descriptions (it was getting to be long).

#486 Closing Issue Documentation: added reviewing dialog

---

dail/closed-case-new-hire.vbs
dail/dail-scrubber.vbs

Built specifically for KW to complete cleaning of CCL DAILs.

#1094 - Closed Case New Hire DAIL Support

---

notes/application-check.vbs

Added specific messaging around the fact that sometimes there is a Display Limit issue that causes us to not be able to read Pending details. The script end procedure is not clear for these cases because it states they are not pending, which may not be true. 
Additional clarity added to the end message here.

#1105 NOTES - Application Check - messaging for PND2 Display Limit

---

admin/on-demand-notes.vbs

Added new closing issue documentation

#1115 ADMIN - ON DEMAND: removed denial info

---

bulk/dail-report.vbs

There have been reports of the stats section erroring when being created. Unable to reliably reproduce this error. The convention for iterating the excel row doesn't match the project convention and this may cause a stability issue, updating to prevent this possibility.

#260 BULK - DAIL Report - update excel row iteration

---

notes/caf.vbs

Created a new variable to collect all of the UNEA income and add it to the rest of the income.

#1097 NOTES - CAF - determining the starting UNEA amount for EXP

---

actions/job-change-reported.vbs

If we have a job reported that started before the APPL month, everything breaks. Handling to resolve that.

#1090 ACTIONS  Job Change Reported new job before first month

---

FUNCLIB CALL - DESERT ISLAND.vbs
FUNCLIB CALL.vbs
MASTER FUNCTIONS LIBRARY.vbs
bulk/case-transfer.vbs
bulk/rept-actv-list.vbs
bulk/rept-eomc-list.vbs
bulk/rept-inac-list.vbs
bulk/rept-mams-list.vbs
bulk/rept-mfcm-list.vbs
bulk/rept-mont-list.vbs
bulk/rept-mrsr-list.vbs
bulk/rept-pnd1-list.vbs
bulk/rept-pnd2-list.vbs
bulk/rept-revs-list.vbs
bulk/rept-revw-list.vbs

Cleaning up the functions and function calls. 
#1079 updated the function in the FuncLib, and removed local calls,
#1078 updated instructions for PF13-24
#1077 removed/retired
#1076 updated and added DESERT ISLAND FuncLib call

All the func lib

---

admin/cs-good-cause.vbs
dail/catch-all.vbs
dail/incarceration.vbs
dail/medi-check.vbs
dail/new-hire-ndnh.vbs
dail/new-hire.vbs
deu/bulk-match-cleared.vbs
deu/match-cleared.vbs
deu/overpayment-claim-entered.vbs
iv-e/ive-adoption-assistance.vbs
iv-e/ive-ma-needy-child.vbs
notes/appeals.vbs
notes/application-check.vbs
notes/application-received.vbs
notes/avs.vbs
notes/change-reported.vbs
notes/documents-received.vbs
notes/health-care-transition.vbs
notes/imig-status.vbs
notes/returned-mail.vbs
notes/smrt.vbs
shelter/shelter-change-reported.vbs

1139 ecf verbiage updates

---

notes/application-received.vbs
notes/subsequent-application.vbs

New script file to support case assignment work when a subsequent application is received.
I plan to pull this in Monday morning for testing by CA.
This pull does not have updates to CLOS or the CA menu updates. I will complete those when I am ready to pull the changes in.

#1104 New Script - NOTES - Subsequent Applications

---

TYPE - NEW SCRIPT TEMPLATE.vbs

Added more comments, change log, dialog naming and calling directions, mandatory field handling and functions, general script steps, closing issue doc reminder and more.....

#981 TYPE - NEW SCRIPT TEMPLATE: Updated template

---

notes/subsequent-application.vbs

Testing reports updates. Dlg handling mostly.

#1104 - NOTES- Subsequent Apps - dlg msg handling

---

notes/application-received.vbs

Bug on the handling for if a second application is for HC only. The App Received script needs to handle for these cases and avoid the duplicate processing.

#1104 NOTES - Application Received - 2 apps - one is HC

---

admin/poli-temp-monthly-updates.vbs
utilities/poli-temp-list.vbs

Addressing issues #1172 and #1163.

All the poli temp

---

MASTER FUNCTIONS LIBRARY.vbs

Update to the information given to workers when check_for_MAXIS cannot find MAXIS.

#1165 - FUNC LIB - check_for_maxis verbiage change

---

admin/review-report.vbs

Last step to allow REVIEW REPORT to be able to run statistics multiple times per day.

#1085 ADMIN -  Review Report only create table on stats once

---

notes/interview.vbs

So apparently we were redirecting to Interview Completed... ugh
Changed it to be just a message and continue on to work.

#560 NOTES - Interview - removal of redirect or script end for NOT CAF

---

COMPLETE LIST OF SCRIPTS.vbs

Adding the policy reference information to CLOS for SMRT

#51 CLOS - adding policy references to SMRT

---

actions/pf11-actions.vbs
admin/tikl-from-list.vbs
bulk/emps.vbs
bulk/ltc-grh-list-generator.vbs
bulk/rept-actv-list.vbs
bulk/rept-pnd2-list.vbs
deu/adh-info-and-hearing.vbs
iv-e/ive-adoption-assistance.vbs
iv-e/ive-elig-review.vbs
iv-e/ive-ive.vbs
iv-e/ive-ma-needy-child.vbs
iv-e/ive-perm-review.vbs
iv-e/ive-trial-home-visit.vbs
notes/appeals.vbs
notes/asset-reduction.vbs
notes/vendor.vbs
shelter/shelter-ces-screening-appt.vbs
shelter/shelter-ea-approved.vbs
shelter/shelter-mandatory-vendor-approved.vbs
shelter/shelter-mandatory-vendor-memo.vbs
shelter/shelter-permanent-housing-found.vbs
shelter/shelter-personal-needs.vbs
shelter/shelter-special-ea.vbs
shelter/shelter-utility-information.vbs
shelter/shelter-voucher-extended.vbs

Only updates on the do...loop coding. Did not add changelogs since it's background functionality.

1180 syntax error in check for password

---

MASTER FUNCTIONS LIBRARY.vbs
actions/abawd-exemption.vbs
actions/add-grh-rate-2-to-mmis.vbs
actions/claim-referral-tracking.vbs
actions/counted-abawd-months.vbs
actions/fiat-ga-rca-into-snap-budget.vbs
actions/shelter-expense-verif-received.vbs
admin/gather-case-phone-number.vbs
managed-care/mc-client-contact.vbs
managed-care/mc-enrollment.vbs
misc/hennepin-favorites-classes.vbs
misc/hennepin-favorites.vbs
nav/nav-mmis-grh.vbs
notes/change-reported.vbs
notes/disaster-food-replacement.vbs
notes/mfip-to-snap-transition.vbs
notices/12-month-contact.vbs
retired-scripts/abawd-fiater.vbs
utilities/uc-verification-request.vbs

No changelog since this is behind the scene updates. Limited updates to only replacing StopScript. All tested for initial errors.

1187 stop script house keeping

---

notes/avs.vbs
utilities/qi-avs-request.vbs

#311 and #1209 Issues

---

notes/application-received.vbs
notes/subsequent-application.vbs

Update the form information.
Update the how app was received.
Change the email verbiage and details.
Align Subsequent application to App Received updates

#1213 NOTES - Application Received - Align script to process and policy steps

---

notes/emergency.vbs

Effective 04/01/2023
Did not add closing issue documentation due to time constraints and due to nature of issue (annual update).

#1224 NOTES - EMERGENCY: Updated 200% FPG

---

notes/hcapp.vbs
notes/imig-ema.vbs
notes/ltc-application-received.vbs

Select testing file redirect to the new HC Evaluation script from:
- HCAPP
- LTC Application Received
- IMIG EMA 
These scripts will all retire in the next weeks and we need testing.

#1218 - Releasing HC Evaluation to Testing - redirects in 3 scripts

---

notes/application-received.vbs
notes/expedited-screening.vbs

Update includes:
- Formating number to a consistent display
- Aligning the numbers using spaces so that the number columns align.

#1220 Expedited Screening CASE NOTE - align and format the numbers to look better

---

notes/overpayment.vbs

-Added numeric validation for claim# and updated respective messaging
- Replaced outdated AR email with HSPH.FAA.Unit.Tin@hennepin.us
- Updated sharepoint Notes - Overpayment/Claim documentation with new email, screenshots and reordered a few lines to match screenshots.

#1222 #1257 - Added numeric validation for claim# and updated AR Email

---

notes/emergency.vbs

I'm updating the instructions right now.

1224 and 1263 - notes emergency

---

Test scripts/Mark/project-noob-mark.vbs

#1251 Mark project noob

---

COMPLETE LIST OF SCRIPTS.vbs
notices/ltc-asset-transfer.vbs

Please review the updates to meet std requirements. Detailed revisions on Issue. Let me know if my sources are not correct, thanks!

1258 update ltc asset transfer proj std

---

notes/closed-programs.vbs

There will be no more access to NOTES - Closed Programs

#1193 - NOTES - Closed Programs - Redirect every run to Eligibility Summary

---

notices/pa-verif-request.vbs

Updated the dropdown option for "PHA (Public Housing form)" to "Request from Third Party (including Public Housing Agencies)" to align with HSR manual. Updated the instructional MsgBox to match the HSR manual instructions.

#1275 Notices - PA Verif Request

---

COMPLETE LIST OF SCRIPTS.vbs

Update the Complete List of Scripts to have the actual Hot Topics that were recently published.

#452 CLOS - Update the Hot Topics info for the scripts

---

COMPLETE LIST OF SCRIPTS.vbs

Update Complete List of Scripts with retirement date for MA Inmate Application WCOM script

#1278 MA Inmate Application WCOM - Update CLOS Retirement Date

---

COMPLETE LIST OF SCRIPTS.vbs
utilities/hot-topics.vbs

Added the Hot Topics script to the CLOS so that we can run it from the UTILITY Menu as well. 
Additional bugs found in the formatting of the display;
- dialog size calculation
- Capitalization in the URLs for the Hot Topics
Bug with a constant name being redefined, changed the name to be HT specific.

#452 UTILITIES - Hot Topics - add to CLOS and some formatting updates

---

COMPLETE LIST OF SCRIPTS.vbs

Updated complete list of scripts for LTC transfer penalty

#1232 - LTC Transfer Penalty Complete List of Scripts update

---

actions/transfer-case.vbs

Updated date validation to ensure dates are in MM/DD/YYYY format. Fixed typos within error messages. Updated tab order on dialogs.

#1254 ACTIONS - TRANSFER CASE: Ensure dates will work for specific formats

---

MASTER FUNCTIONS LIBRARY.vbs

Add CM + 3, CM - 1, CM - 2, and CM - 3 to functions library

#1320 add more date constants to func lib

---

admin/ex-parte-report.vbs
misc/Ex Parte/prep-details.vbs

Created the start of a BULK Report in ADMIN for completing the agency wide steps to support Ex Parte. 
This initial version is able to run the Prep Phase to evaluate cases for Ex Parte, send a SVES/QURY and create a list of VA and UC income for verification. 
This also includes an individual script that displays the details of the discovery done during the prep phase to review the functionality of the script.

#1311 & #1312 Ex Parte - BULK Report for PREP and connect to SQL data

---

notes/health-care-evaluation.vbs

Updates to allow the script work for recertifications.

#129 NOTES - HC Eval - add recert option

---

misc/Ex Parte/1307-Phase-1-Display-Verify-CASE-NOTE-Ex-Parte-Info.vbs
misc/Ex Parte/1309-uc-information-updater.vbs

Add functionality to display, verify, and case note ex parte information

#1307 phase 1   display, verify, and case note ex parte information

---

notes/health-care-evaluation.vbs

Add links for policy and instruction buttons

#1335 Add links for policy and instr btns

---

notes/health-care-evaluation.vbs

Read DISA for waiver information and change the dialog information and layout.
Additionally, change the REVW navigation functionality.

#1307 - Hc Eval - Ex Parte - update REVW nav and dialog layout

---

dail/dail-scrubber.vbs

Tested on a case in inquiry. Worked as expected.

#1343 DAIL - DAIL SCRUBBER: Added new ABAWD message

---

notes/health-care-evaluation.vbs

Added logic to separate phase 1 and phase 2 ex parte determinations. Phase 2 dialog and HC renewal screen validation will need to be updated once we receive further direction from DHS.

#1310 Ex Parte - Phase 2 - Display and CASE/NOTE information/determination

---

Test scripts/Ilse/New Hire Discovery.vbs
admin/dail-12-month-contact.vbs
admin/dail-fmed-deduction.vbs

I tested both ADMIN scripts, the TS doesn't need testing.

1349 dail pick bug

---

notes/hrf.vbs

Did not complete Closing Issue Documentation as we have known major updates to this script coming.

1363 hrf confirmation

---

admin/task-based-dail-capture.vbs

Partial issue pull request. @MDR22 take a look at the function non_actionable_dails to see which DAIL's are also excluded from assignment.

1369 ex parte tikl support 

---

notes/caf.vbs

There was a bug because a pending HC ER was erasing CAF and Interview dates.

#1203 NOTES - CAF - don't read HC or REVW information because we don't care

---

notes/application-received.vbs
notes/expedited-determination.vbs
notes/interview.vbs
notes/subsequent-application.vbs

I think the main issue was the MAXIS_Case_Number error handling in the case number dialog in Application Received, BUT might as well solidify everything that updates the cases pending table.

#1410 Trim Case Number for SQL to be in error

---

admin/resolve-hc-eomc-in-mmis.vbs

This will be the first part of this resolution until we can get it aligned with the FuncLib.

#1425 ADMIN - Resolve HC EOMC - add email output to QI

---

dail/bndx-scrubber.vbs

Added reading and trimming full DAIL message and measurement dail message. Added warning message handling to delete messages not in workers number.

#1422 DAIL - BNDX Scrubber: fixed bug in delete function

---

MASTER FUNCTIONS LIBRARY.vbs
actions/earned-income-budgeting.vbs

This also is the testing call for so many EIB changes: 
#69, #404,  #405, #711, #712, #730, #1095, #1419

#1242 funclib testing script repo update

---

admin/resolve-hc-eomc-in-mmis.vbs

Update to use the function for the email and added closing project documentation.

#1425 ADMIN - Resolved HC EOMC - align email to function library 

---

MASTER FUNCTIONS LIBRARY.vbs
admin/ex-parte-report.vbs
notes/health-care-evaluation.vbs

Updated files:
NOTES - Health Care Evaluation
ADMIN - Ex Parte Report 
Functions Library - determine_program_and_case_status
Functionality:
Updates to BULK run for Phase 1 - cleaner and working
HC Eval - Phase 1 - references STAT information and added PDED
HC Eval - Added Phase 2 support for cases we could not approve
HC Eval - Removed Phase 2 PROBLEM button
FuncLib - fix to IMD and QI1 program reading in the function
More comments will be added after this is pulled in so don't worry about that part - I am working through it - we just have a time crunch.

#1385, #1396, #1399, #1408, #1417, #1440 Ex parte end of july updates

---

MASTER FUNCTIONS LIBRARY.vbs

1369 non actionable dail

---

MASTER FUNCTIONS LIBRARY.vbs

Created function for digital experience in functions lib to standardize the verbiage.

#1037 Created function for digital experience

---

notes/interview.vbs

#1296 - added manual time based on logic and addition/calculation
#1033 - display the worker entered notes from the main script dialog in the Expedited Determination dialog
#1081 - Added detail to the EBT dialog to support the HSR manual page from accounting
#1455 - bug where a CASE/NOTE was not saved

#1296 #1033 #1081 #1455 NOTES - Interview Q3 updates

---

MASTER FUNCTIONS LIBRARY.vbs

2 separate commits: 
- Appointment notice
- NOMI
Let me know what feedback you have if any!

1036 create make appointment &nomi functions

---

COMPLETE LIST OF SCRIPTS.vbs
utilities/hot-topics.vbs

Tested all the new links in CLoS, and the Hot Topics that were added. I got the text issue figured out, so I just need you to take a look at the pull.

1283 comp list of script references

---

MASTER FUNCTIONS LIBRARY.vbs

October mass changes to functions. See commits for source of information for confirming amounts.

1471 october annual function changes

---

dail/postponed-expedited-snap-verifications.vbs

Final update to DAIL - POSTPONED EXP SNAP VERIFICATIONS to utilize new digital_experience function added to functions library after initial branch.

#363 DAIL - POSTPONED EXP SNAP VERIFICATIONS - Utilize digital_experience function

---

MASTER FUNCTIONS LIBRARY.vbs

We recently added the ability of the script ACTIONS - Earned Income Budgeting to 'save your work' and create a txt file cookie with the information from the script run. These files are handled in the functions library to be deleted after a week. This update adds the review in the section in the functions library where these files are deleted to find the files created by earned income budgeting.

#1466 FuncLib - add functionality to remove EIB save your work files from docs folder

---

Test scripts/Ilse/Restart scripts/ADMIN - DAIL 12 MONTH CONTACT RESTART.vbs
Test scripts/Ilse/Restart scripts/ADMIN - DAIL FMED DEDUCTION RESTART.vbs
actions/job-change-reported.vbs
admin/dail-12-month-contact.vbs
admin/dail-fmed-deduction.vbs
admin/individual-appointment-letter.vbs
admin/individual-nomi.vbs
admin/individual-recertification-notices.vbs
admin/on-demand-waiver-applications.vbs
admin/review-report.vbs
dail/fmed-deduction.vbs
dail/overdue-baby.vbs
notes/application-received.vbs
notes/denied-programs.vbs
notes/subsequent-application.vbs
notices/add-wcom.vbs
notices/eligibility-notifier.vbs

Updated individual coding with function for digital experience. 
NOTICES-ADD WCOM leveraged add_words_to_message so I simply updated the words to match the function built.  Let me know if you want something different here.

1458 replace ind digital experience with function

---

MASTER FUNCTIONS LIBRARY.vbs
Test scripts/Ilse/Restart scripts/ADMIN - DAIL 12 MONTH CONTACT RESTART.vbs
Test scripts/Ilse/Restart scripts/ADMIN - DAIL FMED DEDUCTION RESTART.vbs
actions/job-change-reported.vbs
admin/dail-12-month-contact.vbs
admin/dail-fmed-deduction.vbs
admin/individual-appointment-letter.vbs
admin/individual-nomi.vbs
admin/individual-recertification-notices.vbs
admin/on-demand-waiver-applications.vbs
admin/review-report.vbs
dail/fmed-deduction.vbs
dail/overdue-baby.vbs
notes/application-received.vbs
notes/denied-programs.vbs
notes/subsequent-application.vbs
notices/add-wcom.vbs
notices/eligibility-notifier.vbs

Updates: This was a redo of branch update #1458 to:
- Replace individual digital experience code with the DE function
-Update the DE function in the master funcLib in this update. 
Unable to test/need to touch base with other folks when they run these scripts:
- Admin- Individual Recertification Notices @IlseFerris - can you fully test these please! :)
- Notices - Add WCOM @IlseFerris - can you fully test these please! :)
- Actions-Job Change Reported (Ilse and I spoke, this script is a little buggy- removed 5 lines and replaced with 4 lines)
- Admin- On Demand Waiver Applications (Need to connect with QI team once this is pushed to see if they receive errors)
- Admin Review Report (connect with Casey when this is run next)
- Notes-Denied Programs (Ilse and I spoke, don't worry about this …

#1458 redo digital experience update ind code with function

---

admin/expedited-determination-report.vbs

Updates to ADMIN - Expedited Determination Report:
1. Change the reading of user information from Excel to SQL - BUT put it on HOLD while we work on access to the data table
2. Adding the ability to completely reset the HSS list in Excel since this will need to be updated until we can directly access the data table. 
This script is used by KR almost exclusively.

#1034 ADMIN - Expedited Determination Report - using SQL table

---

admin/on-demand-waiver-applications.vbs
admin/review-report.vbs

Admin Rev Report- Corrected issue with appt recert function (duplicate coding) and replaced ind code for nomi-recrt with NOMI_recrt function. 
Admin On Demand Waiver Application- Replaced appt. notice with NOMI appt to correct this issue.

1458 appt notice funct on demand review report

---

MASTER FUNCTIONS LIBRARY.vbs

Updates to the function - access_ADDR_panel to read the phone number correctly and format it nicely.

#1501 FuncLib - PHONE NUMBERS MOVED

---

admin/training-case-creator.vbs

Updates to Training Case Creator with the new phone number positioning on ADDR. 
Tested on a scenario and it worked well. (TRN - 329796)

#1501 - ADMIN - Training Case Creator - ADDR phone number moved

---

COMPLETE LIST OF SCRIPTS.vbs
utilities/uc-verification-request.vbs

Updated the script handling for STAT/MEMB and made a few small tweaks to dialog options. Updated CLOS with policy references. Updated instructions ([saved here](https://hennepin-my.sharepoint.com/:w:/g/personal/mark_riegel_hennepin_us/EW7gaQkiQCVKtbtOBQ-Idh4BTHl8nk3zfVJqSpHuUIPK_g?e=vIuPYe)) and will upload once merged.

#1461 utilities - uc verif request user experience updates

---

COMPLETE LIST OF SCRIPTS.vbs
case-assignment/person-search.vbs

This script was developed by MNIT and does not necessarily follow all of our standards/conventions. So there will be things that do not look quite right, and that's fine for this. 
I have changed only the parts necessary to make the script run in our infrastructure and then some supportive measures for our testers to reduce the burden of testing.

#1514 MNIT Person Search Script add for testing

---

notes/sponsor-income.vbs

This required adding footer month to dialog to allow it to calculate the 130% based on footer month.

#1512 sponsor income uses function to determine 130% FPG

---

COMPLETE LIST OF SCRIPTS.vbs
notes/health-care-transition.vbs

Updated NOTES-HC transition to include person record number if METS case number is not available. 
Updated CLOS to include documentation.

1449 notes hc transition person record number

---

notes/ltc-cola-summary.vbs
notes/ltc-intake-approval.vbs
notes/ltc-ma-approval.vbs

Let's let the people know what is coming.

#1233 Changelog Warnings of upcoming script retirements

---

notices/add-wcom.vbs

Removed functionality (commented out) for temp_disa_abawd_wcom and abawd_child_6_coded_wcom. Updated language for ineligible students. Updated format of dialog.

#1511 Notices - add wcom updates per te02.05.19

---

notes/emergency-exceeds-approval-limit.vbs

New script creation - CASE NOTE only at this time.
CLOS is not in this pull, will do a new pull with CLOS after merge.

#1253 New Script NOTES - Emergency Exceeds Approval Limits

---

notes/appeals.vbs

Added docket number to the initial dialog, and error handling to require the user enter the number for most scenarios on the script. All scenarios now case note the docket number.

#1491 NOTES - Appeals docket number is global

---

actions/ma-fiater-for-grh-msa.vbs

Bug fix - check to make sure things are objects before we treat them like objects. 
This came in as an error report yesterday 10/11 from Gawa. 
Case to test functionality - 1283790

#1533 ACTIONS - MA FIAT GRH-MSA - object bug fix

---

COMPLETE LIST OF SCRIPTS.vbs
admin/report-a-duplicate-unea-panel.vbs

Create a script that will report UNEA panels that are duplicated to support work in Ex Parte.

#1547 New Script - ADMIN - Report a Duplicate UNEA Panel

---

actions/bils-updater.vbs

This change updates actions - bils updater to move check_for_maxis outside of the dialog structure. All other scripts involved in this issue are being fixed elsewhere.

#1166 audit check_for_maxis

---

notes/health-care-evaluation.vbs

Left this under same issue, IMIG was having trouble with misaligned hh member arrays - added a loop to check and match member numbers before evaluating the values in the HEALTH_CARE_MEMBER array.

#1554 fixing problems with the IMIG portion of the script

---

MASTER FUNCTIONS LIBRARY.vbs

Refer to 2024 Payroll calendar sent via email.

#1557 Funclib Holiday_Array: Updated w/ 2024 holiday dates

---

MASTER FUNCTIONS LIBRARY.vbs

create_mainframe_friendly_date will now self-identify the date format it is writing to. 
Current scripts using this function:
Utilities - update check dates
actions - job change reported
DAIL - cses scrubber
admin - ex parte

#1256 universal date function

---

actions/transfer-case.vbs

Excluded time cases for MA need to be completed on line 15, and this handling was not in the IF...statement.

#1566 ACTIONS - TRANSFER CASE: Fixed MA excluded time bug

---

managed-care/enrollment.vbs

Dates can be found here: https://mn.gov/dhs/assets/2024-managed-care-key-dates_tcm1053-599878.pdf 
https://mn.gov/dhs/partners-and-providers/policies-procedures/minnesota-health-care-programs/provider/mcos/contract-information-forms-and-resources/health-plan-systems-workgroup/

#1529 MHC - Enrollment - Updated enrollment cutoff dates for 2024

---

actions/pf11-actions.vbs

Added handling to navigate to SELF and then check MAXIS environment. Script will end if not run in production.

#1553 Ensure script is only run in production

---

admin/ex-parte-report.vbs

Updating the script to do the following things:
1. Create the Excel files at the beginning of the run and save it. 
2. If the script is restarted, check to see if the Excel File has been already created and reopen.
3. Update the spreadsheets as the script runs. 
4. Once the list is fully processed, save and close the files. Then email these files as needed.
This is basically a restructure of how the Excel is handled because we want it handled more programmatically.

#1572 ADMIN - Ex Parte - set up verifs list to save first

---

COMPLETE LIST OF SCRIPTS.vbs

Updated CLOS for LTC by removing specific handling for LTC since documents are now stored in NOTES folder with all other notes scripts

#1446 Updated CLOS for LTC

---

admin/bulk-poli-temp-to-word.vbs
admin/poli-temp-monthly-updates.vbs
utilities/poli-temp-to-word.vbs

Updated 3 scripts to change formatting to include leading whitespace and correct paragraph formatting when pulling poli-temp to word. 
Scripts changed:
Admin - Bulk Poli Temp To Word
Admin - Poli Temp Monthly Updates
Utilities - Poli Temp to Word

#1542 poli temp to word whitespace formatting

---

notes/eligibility-summary.vbs

Updated the EA 200% FPG Limits to the 4/2023 limits from the [Combined Manual](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=cm_00161801).

#1588 Update to 4/2023 200% FPG limits for EA

---

dail/ltc-remedial-care.vbs

Amounts listed at [this](https://hcopub.dhs.state.mn.us/epm/appendix_f.htm) location
corrected sp errors.
removed msgbox

#1596 DAIL - REMEDIAL CARE: Updated 01/24 RC amount

---

MASTER FUNCTIONS LIBRARY.vbs

Ten day cut off dates are listed in TE19.132

1594 december annual updates

---

MASTER FUNCTIONS LIBRARY.vbs
notes/eligibility-summary.vbs
notes/emergency.vbs

Added function determine_200_percent_of_FPG() to Func Lib. It outputs the 200% FPG amount based on the program (EA, EGA, or SNAP), application date (if applicable), and household size.
Updated the NOTES - ELIG SUMMARY and NOTES - EMERGENCY scripts to utilize the new function.

#1541 Create function to determine 200% of fpg

---

notes/health-care-evaluation.vbs

Discussed with Casey and working on incorportating the needed functionality.

1565 notes hc eval update case note

---

COMPLETE LIST OF SCRIPTS.vbs
actions/transfer-case.vbs

-Removed HSR manual button- link no longer exists
-Replaced broken links
-Updated POLI TEMP with sharepoint link
-Added transfer to another county button to dialog 
-Updated CLOS

1590 actions transfer case broken links

---

notes/health-care-evaluation.vbs

Bug reported by AGK that if 'Complete' was pressed, then 'No' - complete would come up with every button push - which is annoying. This was a boolean reset issue.

#1601 NOTES - HC Eval leave loop for complete - boolean update

---

dail/cola-review-and-approve.vbs
dail/dail-scrubber.vbs

Updates to:
DAIL - COLA Review and Approve
DAIL - DAIL Scrubber
This will support COLA processing

#1518 DAIL - COLA Review and Approve - align to project updates

---

actions/ma-fiater-for-grh-msa.vbs

The script was trying to FIAT SSI income and include a COLA deduction - which isn't needed for SSI income since it is excluded entirely. 
Added handling to not do the COLA thing if it is SSI.

#1602 - ACTIONS - MA FIATer for MSA/GRH - error with COLA and SSI 

---

COMPLETE LIST OF SCRIPTS.vbs
notes/SNAP-waived-interview.vbs
notes/main-menu.vbs

Pull request has the new script and CLOS updates.

#1282 New Script - SNAP Waived Interview

---

actions/tlr-screening.vbs

Instructions are on SharePoint. 
Will add to CLoS in separate pull.

1606 tlr screening

---

COMPLETE LIST OF SCRIPTS.vbs

Will be adding hot topic links later today when published.

#1606 CLoS: Added TLR Screening, retired ABAWD EXEMPTION

---

notes/snap-waived-interview.vbs

Fixes numerous bugs in dialogs and case noting.

#1282 snap waived interview bug fixes

---

Test scripts/Megan/Doc Rec Multi D Dialog.vbs
Test scripts/Megan/Doc Rec Testing Dialog.vbs

test script- merging into master

Doc rec 425 305 78 67 77 79 999 1298

---

MASTER FUNCTIONS LIBRARY.vbs
utilities/report-to-the-bzst.vbs

Updated 2 files: Master Func lib and Report to BZST with functionality to attach txt file to error emails for script end procedure w/ error reporting and report to BZST.

1500 eib attach file to error emails

---

admin/review-report.vbs

The U Code Worklist has been listing the wrong cash program. Looks like we were reading the wrong column for the cash programs for Review Report. 
Double checked the MONT Report and it appears this one was fine (probably where I copied the code from originally).

#1619 ADMIN - Review Report - U Code list - cash progs wrong column

---

admin/on-demand-waiver-applications.vbs

Currently cases with that are over 30 days old are added to the worklist for review by a QI worker. We are stopping this review as we need a more holistic process to handle for cases pending over 30 days. 
NOTE - the changes in the first part of the script are to remove a specific case handling process that was put in place during some testing issues that arose.

#1639 ADMIN - On Demand Apps - no assignment for cases over day 30

---

actions/transfer-case.vbs

Adding come additional verbiage for the inner county closing message.

#1645 ACTIONS - Transfer Case - closing message additional verbiage

---

actions/ma-fiater-for-grh-msa.vbs

Changed the dialog parameters for deeming income and updated the dialog used for the deeming members selection.
Additionally moved the testing_run to be true ONLY when deeming income was selected. We seem to have sufficient testing for the standard run. 
If you need a case to test on the error report from TE in the team email has one with 2 members that deeming functionality can be tested. 
Selected all team members for review, but I am looking for two reviews.

#1646 ACTIONS - MA FIATer for MSA-GRH - deeming functionality minor bugs

---

actions/tlr-screening.vbs

UAT updates added for selecting the month/year and updating through CM + 1.

1606 tlr enhancements

---

notes/health-care-evaluation.vbs

Added form to droplist selection. There is a short form to create but otherwise, there is no different functionality based on form type.

#1657 NOTES - HC Eval - add Form 8262 to selection

---

admin/task-based-dail-capture.vbs

Cleaned up a lot of the unnecessary code, and added new Closing Issue Documentation. Can be run to test with the default settings for the dialog in place. It won't mess anything up if it's run for assignments more than once.

1434 tb dail capture updates

---

MASTER FUNCTIONS LIBRARY.vbs

Added 2 PEPR messages that are not from this_month or last_month, but cannot be deleted.

#1665 FuncLib: non_actionable_dails: Added PEPR msg support

---

bulk/find-maepd-medi-cei.vbs

Added additional information to Excel output and added agency wide supports.

255 bulk ma epd enhancements

---

MASTER FUNCTIONS LIBRARY.vbs

Why did this take me so long to find... ugh - clearly still getting better

#1678 Functions Library - correct variable for DWP case status

---

admin/ex-parte-report.vbs

#1677 ADMIN - ExParte Report - COLA handling

---

admin/resolve-hc-eomc-in-mmis.vbs

Changing some words to make the direction for the work list have a different perspective.

#1688 ADMIN - Resolve HC EOMC - Budget Error Worklist verbiage update

---

admin/on-demand-waiver-applications.vbs

#1687 ADMIN - On Demand Waiver Application - Hide Excels

---

notes/subsequent-application.vbs

Removed the memo wording to use the function that defines the appt notice wording centrally.

#1691 - NOTES - Subsequent App - MEMO to use Function

---

notes/avs.vbs
utilities/qi-avs-request.vbs

1662 avs renewals

---

notes/health-care-evaluation.vbs

Additional support to Ex parte Phase 1 group. 
This will be difficult to test, but it is an isolated user group, we should be able to control the testing starting the 1st of the March. 
I will need to put together testing details next Wed/Thru for the Ex Parte group.

#1686 NOTES - HC Eval - Add Mixed HH Note

---

notes/mfip-orientation.vbs

1705 Fix minor typos for "orientation"

---

notes/hrf.vbs

-Removed elig details from dialogs, readscreens, and case notes 
-Updated change log
-Added closing issue documentation

1682 notes hrf remove elig details

---

notes/emergency.vbs

#1707 NOTES - Emergency - CASE/NOTE Incorrect on Screening Info

---

MASTER FUNCTIONS LIBRARY.vbs

-Removed unnecessary msgbox commented out
-Changed CASE/NOTE edit mode check to evaluate based on the panel name rather than mode and CASE/NOTE panel 
-Add option to cancel script and submit error report

#925 AUDIT - start_a_blank_CASE_NOTE()

---

admin/individual-on-demand-notices.vbs

This is the new script creation. We will have another pull request with updates to CLOS, and to retire the 3 scripts this new script replaces.

#1685 New Script - ADMIN - Individual On Demand Notices

---

actions/transfer-case.vbs

Updated resource links for TE and sharepoint

1714 actions transfer case link updates

---

dail/new-hire-ndnh.vbs

Updated INFC dialog to display employer name

1709 DAIL - NEW HIRE NDNH, indicate employer name on INFC dialog

---

MASTER FUNCTIONS LIBRARY.vbs

-Update 200% FPG for April 2023 for EA and EGA
-Separate programs for easier future 200% FPG updates 
-Update handling for EA and EGA applications with no date to determine 200% FPG amounts based on date of script run
-Update EGA to only handle for applications before or after 4/1/24 (not before 4/1/23)

#1717 Update function determine_200_percent_of_FPG for April 2024 Changes

---

actions/earned-income-budgeting.vbs

#1731 ACTIONS - Earned Income Budgeting - JOBS Panel find bug fix

---

MASTER FUNCTIONS LIBRARY.vbs

Include screen code in error reporting

925 Function start_a_blank_case_note - Include screen code in error reporting

---

notes/application-received.vbs
notes/subsequent-application.vbs

Adding the ability to read up to 3 additional app dates.

#1742 NOTES - Subsequent Application - 3 app dates

---

actions/banked-months-updater.vbs

Updated ACTIONS - BANKED MONTHS UPDATER for new directions. Team chat will have the gist of the new changes. Training case #328740 can be used to test.

1716 banked months updater

---

COMPLETE LIST OF SCRIPTS.vbs

Adding UTILITIES - ELIG Results to Word to CLOS for access.

#907 CLOS - add ELIG Results to Word

---

admin/qc-results.vbs
notices/add-wcom.vbs
notices/ma-epd-no-initial-premium.vbs

Updated scripts to handle for update to WCOM to allow for two pages/30 lines.

#1736 WCOM - updates due to two pages

---

deu/match-cleared.vbs

Removal of overpayment functionality from DEU - MATCH CLEARED. This has now been removed from all match-based scripts and we now have the just one overpayment functionality to work with. 
Instructions updated. Not great, but they will do. 
Will add policy and procedural references in separate pull. I have the CLoS out in another pull request.

1764 wage match op clean up

---

admin/ex-parte-report.vbs

Includes all cases in phase 1 that have SSI income.
Includes all cases in phase 1 that have at least 1 member passing ex-parte

#1752 Ex Parte Phase 1 person-based and SSI changes

---

COMPLETE LIST OF SCRIPTS.vbs

@C-Love that function in ALL SCRIPTS continues to be so helpful. Thank you!

#1764 CLoS: Updated policy & procedures for DEU - MATCH CLEARED

---

MASTER FUNCTIONS LIBRARY.vbs
admin/on-demand-waiver-applications.vbs

Need to review with whole team. Unsure if the FuncLib changes are the best option.

#1777 Update On Demand End Message and Keep MEMO limit from failing BULK run

---

notes/health-care-evaluation.vbs

These fixes account for the new field locations on the STAT/REVW hc renewal popup - this is a temporary change to maintain script functionality at this time.
Full error handling for new ex parte fields on HCMI will be added in the future.

NOTES - HC Evaluation emergency fix to HC renewal popup fields

---

notes/eligibility-summary.vbs

Added handling to check for 'U' code on REVW and MONT panels for each month until cm+1. Moved this to follow the initial dialog instead of later in the script to allow for REVW/MONT panel updates or program approvals while the script is still running. 
Also fixed a bug at the same time

1250 elig summ program u code handling

---

dail/new-hire-ndnh.vbs

SL reported INFC would not clear.
Removed match_row for use of row variable
removed msgboxes and added script end procedures
cleared_confirmation condition was not set up correctly. Fixed. Used write_value_and_transmit when making updates
Streamlined writing to INFC.

#1773 DAIL - NEW HIRE NDNH: Streamlined the experience in the code

---

notes/application-received.vbs

Reminder code is same code that's in ACTIONS - TRANSFER CASE for consistency. CA needs this in place right away, so going to pull in myself.

#1804 NOTES - APPLICATION RECEIVED: added transfer reminder

---

notes/application-received.vbs

Added into dialog experience vs. VBYesNo

#1804 NOTES - APP REC'D: updated transfer confirm experience

---

notes/eligibility-summary.vbs

Updates to Eligibility summary:
1. Better handling of Expedited in CASE/NOTE. Making sure the header only lists the months that are approved and the benefit amount is only for approved months. This is primarily for cases that will close SNAP due to postponed verifications, MAXIS looks kind of weird in these situations.
2. Adding a display of NON-Cooperation into CASE/NOTE from detail in STAT/DISQ. This also applies to MFIP and DWP cases. 
3. Update to the display of Shelter Expense for cases that are approved and exceed the MAX shelter expense to indicate that there is no limit to this expense deduction.
4. Added different information to the SNAP closure CASE/NOTE for cases in a SNAP to MFIP transition.
5. Created the ability to read cases that are indicated as homeless and have a …

#123 NOTES - Elig Summ - SNAP Enhancements

---

MASTER FUNCTIONS LIBRARY.vbs

Updated Coordinates and updated format/handling issues. 
-Updated phone number coordinates for new layout 
-Revised State list to remove dash -- this allowed the variable to populate the dialog if a value existed 
-Mail_state and resi_state leverages state list 
-Updated addr_eff_date handling so it has xx/xx/xx format 
-Updated mail_state handling so original and current matched -- otherwise it was updating addr when there wasn't an update
-Revised handling for writing address on 1 or 2 lines

1813 func lib addr hest shel function

---

deu/match-cleared.vbs

Changed to cancel w/o confirmation
Added if statement if out of county code is found to check for blank county name and if found gives the user a different script end procedure message.

#1824 DEU - MATCH CLEARED: Updated messaging for blank co workers

---

dail/new-hire-ndnh.vbs
dail/new-hire.vbs

Add HH Memb and Hire Date from NDNH and SDNH to TIKL.

1768 DAIL - New Hire & New Hire NDNH, update tikl language

---

notes/application-received.vbs

Will additionally update documentation of this transfer process with these new caseloads.

#1821 NOTES - App Recvd - Add HCMC and North Memorial Contracted Caseloads

---

dail/bndx-scrubber.vbs

Added readscreen of SSN on INFC and formatted SSN on MEMB to allow for appropriate validation check.

#1834 BNDX DAIL SCRUBBER -- Added readscreen for SSN on INFC and formatted SSN from Memb for validation check

---

notes/approved-programs.vbs

Changelog for final sundown - WITH ASCII ART.
Also updated some of the information and functionality in the Elig Summ redirect.

#1194 NOTES - Approved Programs - Final sundown message

---

dail/ltc-remedial-care.vbs

Updated 07/24 amounts
Also fixed inhibiting bug.

1849 remedial care

---

COMPLETE LIST OF SCRIPTS.vbs
utilities/data-access-test.vbs

New script to test access to tables or other data structures

#1825 New script - UTILITIES - Data Access Test

---

notes/returned-mail.vbs

Updated if statements to match returned mail types after I had changed capitalization of options. Thanks Megan for catching!

#1863 NOTES - RETURNED MAIL, Update if statements to match returned mail type

---

MASTER FUNCTIONS LIBRARY.vbs

I tested this on case 2229996 when used in Elig Summ.

#1869 FuncLib - find_last_approved_ELIG_version - MSA 99 code might not work

---

CLOSING ISSUE DOCUMENTATION.vbs
TYPE - NEW SCRIPT TEMPLATE.vbs

Updates to help add functionality and support to the scripts. Additionally, add some useful functionality to the templates for a new script and closing project documentation. 
These templates will take the place of a function to 'get_this_script_started'. 
There will be a separate pull request to remove the start of the function from the FuncLib - but the file was in a branch when this part was done.

#125 Script Consistency and Ease of Use

---

COMPLETE LIST OF SCRIPTS.vbs
notes/disaster-food-replacement.vbs
notes/ebt-benefits-stolen.vbs

New script to reflect EBT Stolen Benefits process - see POLI/TEMP 02.11.126, 02.11.127, and 02.11.128. CASE/NOTES information about the request and then can prepare a SPEC/MEMO depending on whether request is approved or denied. Script instructions are [saved here](https://hennepin.sharepoint.com/:w:/r/teams/hs-economic-supports-hub/BlueZone_Script_Instructions/NOTES/NOTES%20-%20EBT%20STOLEN%20BENEFITS.docx?d=wbb620feb150642b982c0aaf6eb4a8280&csf=1&web=1&e=VSGKdb).

#1473 Replacing Stolen EBT Food

---

notes/eligibility-summary.vbs

Added the ability to document vendor payments as a part of the MFIP approval and eligibility.

#123 elig summ MFIP Vendor and phrasing updates

---

notes/returned-mail.vbs

Update links to POLI/TEMP to go to SharePoint instead of POLI/TEMP in MAXIS

#1874 Link to SharePoint POLI/TEMPs, add changelog

---

admin/review-report.vbs

Removing all coding around creating return to standard HC case notes in ADMIN Review Report. Will update HC Eval once it is not being updated. 
I will be testing this through on the 1st as a part of routine runs.

#1792 - ADMIN - Review Report - remove HC Standard Policy CASE NOTE

---

COMPLETE LIST OF SCRIPTS.vbs

Corrected script name in complete list of scripts, which had been causing errors when users tried to access script

#1473 NOTES - EBT STOLEN BENEFITS, correct script name

---

notes/health-care-evaluation.vbs

-Casenotes total assets by member 
-Dialog displays total assets by member
-For cars, exclude Use Code 4 and 5 from asset total. For all other codes, exclude the highest valued vehicle.
-For real estate, do not sum those with Property Status of "home residence"
-Fixed spelling issue 
-Fixed secu_string casenoting

1630 notes health care eval asset total 

---

notes/eligibility-summary.vbs

Final functionality completed:
- Notes inputs for prorated benefits (Does not apply to MSA, EMER, or HC
- Notes inputs for FIATed benefits (does not apply to GA, EMER, or HC)
- Tips and Tricks button for Verifs date
- Stats timing update
- Closing project documentation
- some small HC bugs

#123 NOTES - Eligibility Summary - Core Functionality finished

---

notes/health-care-evaluation.vbs

There is a round function that seems to work.

#1630 NOTES - HC Eval - cInt limited to +-32767 - use round

---

notes/health-care-evaluation.vbs

Fixes ex parte phase 1 evaluation to function when there are more than 2 members on healthcare.

1776 HC Eval ex parte multi-member-households

---

admin/on-demand-dashboard.vbs

This functionality is just to ensure the completion of the End of Day process doesn't break entirely if the connection is lost. Using the array to bridge the gap offers a chance for the end of day functionality to fail in the middle. This might cause the need to restart the functionality but no information would be lost. 
We are basically just mitigating interrupted runs due to worker error or connection issues.

#1868 ADMIN - On Demand Dashboard - Update worklog directly from SQL - no Array

---

actions/transfer-case.vbs

Error reported if a space is in the field with the x-number as it counts the characters incorrectly.

#1905 ACTIONS - Transfer Case - trim x-number

---

MASTER FUNCTIONS LIBRARY.vbs

Update handling for function navigate_to_MAXIS_screen to include handling for EA history panel screen.

#1910 NOTES - EMERGENCY & Function navigate_to_MAXIS_screen, add handling for navigating away from EA history panel

---

admin/on-demand-dashboard.vbs
admin/on-demand-waiver-applications.vbs

With SNAP Interview Waiver we do not need to check each misaligned interview every single day. Update to allow a week between reviews.

#1868 On Demand Apps - Interview Align - do not review every day

---

misc/faa-health-care-information-report.vbs

Medicare added to HC Information Report. I have a list of PMI's for testing.

1881 hc information report medicare

---

MASTER FUNCTIONS LIBRARY.vbs
Test scripts/Ilse/abawd-report-dhs-discrepancy-reports.vbs
actions/tlr-screening.vbs

This one has the funclib in it now.

1860 military service tlr

---

notes/ebt-benefits-stolen.vbs

Minor tweak to allow user to enter custom explanation for denial of request for SPEC/MEMO

#1473 NOTES - EBT BENEFITS STOLEN, Update error handling for SPEC/MEMO denial dialog

---

notes/grh-non-hrf-postpay.vbs

Updated script to align with current script guidelines:
- Utilize script functions to perform sorting of dates instead of Excel
- Updated dialogs and script function to match script standards
- Did not add vnd_addr_check and pben_check_IAA_dates functions to FuncLib - didn't seem to be necessary to add to FuncLib but can do that if needed; replaced MAXIS_dialog_navigation2 with MAXIS_dialog_navigation function
- Performed general cleanup of script

#485 NOTES - GRH NON HRF POSTPAY, evaluate script and functions

---

notes/application-received.vbs

Clarified the logic for App Received when dealing with GRH cases. These cases should not be transferred as often and we need a split between adults and families.

#1811 - App Recvd - GRH transfer Process Update

---

notes/eligibility-summary.vbs

We cannot easily separate the checks because they are not associated with a specific member.
The resolution is to list all of the MF Special Diet details for all members and combine the checks.

#1923 NOTES - Elig Summ - MF Spec Diet allow multiple Members

---

notes/interview.vbs

Removed information on voluntary quit (DHS-2707), no longer required to review at interview.
Replaced old work registration message with SNAP Work Rules information, and added button to review list of exemptions.

#689 Work rules added to interview.

---

COMPLETE LIST OF SCRIPTS.vbs
utilities/all-scripts.vbs

Updated Utilities All Scripts to create hyperlink for TE Resources 
Updated CLOS for TE resources that had incorrect titling that broke the new functionality

1464 utilities all scripts and clos hyperlink functionality for te resources

---

nav/nav-find-memb-in-mmis.vbs

CLoS will be handled after the pull (it was checked out before my branch)

#37 New Script - NAV - Find MEMB in MMIS

---

notes/health-care-evaluation.vbs

Updated error functionality to: 
- Require review of BILS information if a BILS panel exists
- Require that user enters notes about each type of income (BUSI, UNEA, JOBS) if the income exists. If the income does not exist, it does not require notes to be added

1364 NOTES - HC EVAL, require some review

---

admin/review-report.vbs

File path updated. I ran stats one time through to ensure it worked. 
Sync of the folder is required for this to work.

#1945 ADMIN - Review Report - Stats File Path Change

---

notes/eligibility-summary.vbs

Need better review of the month to find the right spenddown type and match to the correct data.

#1948 NOTES - Elig Summ - HC Spenddown Type Bug

---

notes/documents-received-testing.vbs

Fixed a few quicks things based on feedback so they don't sit until my return.

#425 Simple fixes based on feedback

---

notes/eligibility-summary.vbs

How about we stop getting a million emails. 
I have reviewed this functionality for these warning and quality control review emails are now going to BT. 
There was one issue in evaluating Waiver Obligation and I had to add criteria around this being assessed at $0. 
There was also an issue when the worker selected to not enter the HC Case note - the Ex Parte details still operate and they should not. Updated the logic to skip these steps if the worker says 'No - but continue the script' in the Remedial Care warning pop-up.

#1958 NOTES - Elig Summ - HC Remedial Care QCR to BT

---

MASTER FUNCTIONS LIBRARY.vbs
admin/dail-ccd.vbs

Both updates tested and working as intended.

1969 ga mass change

---

actions/ma-fiater-for-grh-msa.vbs

Small change to add a transmit when needed to get into BBUD

#1977 MSA-GRH Fiater issues with elig navigation

---

actions/earned-income-budgeting.vbs

These updates allow workers to specifically identify the SemiMonthly pay dates because the script sometimes gets the determination wrong. It would be hard to make the script perfect but allowing more visibility and an override will make the script work more often. 
Updates:
- Create a function to display and update the SemiMonthly pay dates so it can be easily called. 
- Add a display of the semi-monthly pay dates to the confirmation dialog.
- Add a button to call the SemiMonthly dates dialog.
There were also a few bugs discovered while fixing the issue.

#1613 ACTIONS - EIB - update SemiMonthly dates handling

---

notes/eligibility-summary.vbs

In reviewing some of the QCR information it was found that the MSA budget is reading it incorrectly.

#1971 NOTES - Elig Summ - bug in reading and eval MSA

---

admin/resolve-hc-eomc-in-mmis.vbs

I don't know that this will be an ongoing issue but since a similar result happened on another script, I was thinking we could save this to record the issue/solution and maybe remember it.

#1994 ADMIN - Resolve HC EOMC in MMIS - bug with NAT error

---

notes/health-care-evaluation.vbs

Confirmed with BT that the phrasing and functionality will be supportive.

#1965 NOTES - HC Eval - Add Remedial Care Reminder

---

notes/application-received.vbs

If Pending is not found on CASE/CURR - we need to check REPT/PND2 before cancelling out of the script.

#2002 NOTES - App Recvd - second cash pending bug fix

---

iv-e/adoption-assistance.vbs

Report from IV-E Workers that the details of these two options should be aligned in this way.

#1376 IVE - Adoption Assistance - switch close and placement ended

---

notes/documents-received-testing.vbs

- Revised DIET functionality to only update DIET in MAXIS with the highest $$ diet of those that overlap 
- Updated Shetler form to capture form details, replaced checkbox to update ADDR, HEST, SHEL with buttons as well

425 documents received updated dashboard feel and new forms

---

notes/eligibility-summary.vbs

Updated thrifty food plan [amounts for 10/24](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=CM_00221201)

#2013 NOTES - ELIGIBILITY SUMMARY, update thrifty food plan amounts for 10/24 

---

notes/interview.vbs

Shortened rights and responsibilities dialog verbiage 
Checkbox feature should be setup to work with the save_work function.

1993 notes interview rights and responsibilities

---

notes/disaster-food-replacement.vbs

Improve dialog error handling to ensure that all DHS-1609 dates are filled out when request is approved

#2005 NOTES - DISASTER FOOD REPLACEMENT, improve dialog error handling

---

admin/review-report.vbs

Include HC in the End of Processing Month script runs

#388 Review Report - Add Autoclose CASE NOTE for HC

---

managed-care/enrollment.vbs

Set variables for open enrollment processing for 2025.

#2015 MHC - Enrollment -  set for 2025 Open Enrollment

---

MASTER FUNCTIONS LIBRARY.vbs
notes/documents-received.vbs
notes/eligibility-summary.vbs

Moved thrifty food plan function to func lib and updated individual scripts

1987 func lib move determine thrify food plan to funclib

---

Test scripts/Ilse/Temp Files for DHS HS/hss-service-authorization-update.vbs
misc/hss-service-authorization-update.vbs

Updates have been sent to DHS via text file for testing. Rates changing for 2024 is the only update.

1781 housing support dhs rate updates

---

deu/view-infc.vbs

Working on instructions now. Not in CLOS yet. It's in another pull request currently.

2006 deu   view infc

---

notes/ebt-benefits-stolen.vbs

Updated CASE/NOTE format to align with SPEC/MEMO

#2023 NOTES - EBT BENEFITS STOLEN, Update CASE/NOTE format to align with SPEC/MEMO

---

notes/interview-summary.vbs
notes/interview.vbs

Updates to both Interview and Interview summary so that Interview Summary can be accessed from the Interview script.

#1944 Release Interview Summary

---

notes/documents-received.vbs

Added functionality: If Diet form is completed for MFIP Active/Pending case, it will email basic case details to the diet team. This will serve as a notification to review address any discrepancies and issue benefits if applicable. 
Also updated the video link to new location #2039

2034 notes doc rec add mfip email functionality & updated video link 

---

notes/snap-waived-interview.vbs

Adding msgbox reminding waiver is ending.
Will retire the script using the same branch next week.

#1782 Added msgbox reminding users waiver is ending

---

notes/health-care-evaluation.vbs

Added a limit of reading 2 panels worth of BILS so that it does not exceed the dialog.

#2056 BILS dialog bug fix

---

admin/review-report.vbs

Update Review Report to send notices for all cases with an interview requirements as the interview waiver has ended.
Ran through Appointment Notices today with no issues.
Additionally added a a call to save the workbook after the Appointment Notice and NOMI runs because I have had some issues with those not being saved at the end of the script run.

#1753 ADMIN - Review Report - Restart SNAP Appt Notices

---

notes/eligibility-summary.vbs

Add handling to turn '?' entries to become 0 for calculations

#2061 - Elig Summ - SHEL Question Marks are 0 amount

---

notes/interview.vbs

Added emergency questions to script:
- Added separate dialog tab for emergency questions with error handling
- Updated save your work functionality for emergency questions
- Updated script lowdown to include emergency questions
- Responses to emergency questions will write to PDF and CASE/NOTE

#892 NOTES - INTERVIEW, Add emergency questions

---

notes/documents-received.vbs

fixed usage of blank case note in doc received on branch with func lib updates

#2070 fixed bug related to start blank case note

---

notes/interview.vbs

-Reviewed dialogs for combox opportunities #1539
-Script updates ADDR if Update Information is selected #568
-Added housing support questions to ADDR dialog #1198
-Script updates HEST if persons paying is identified and heat/ac, electric, or phone is noted. Need to update HEST function once FuncLib is available to ensure we are clearing fields that do not have an entry.  #603
-Bug: Added edrs_ntoes_for_case to case notes #2055

568 1198 1539 2055 603 notes interview revisions

---

MASTER FUNCTIONS LIBRARY.vbs
notes/documents-received.vbs

Updated ADDR: Updated handling of which month to update ADDR in and maintain variables after. Connected to #568.
Updated HEST: connected to issue #603. Updated HEST function to clear/blank out fields in case there is already info on the panel for that field. 
Updated Doc Rec: Impacted by ADDR update, no longer needed handing within doc rec for which month to update ADDR in.

2075 update addr & hest

---

admin/on-demand-waiver-applications.vbs

Folder created if missing and moved if too old. 
No rush on this review, November is correctly set up, so it won't be particularly relevant until December.
I ran this to set up November correctly.

#2072 On Demand Applications - automate folder management

---

misc/interview-forms-classes.vbs
notes/interview-summary.vbs
notes/interview.vbs

Incorporates the script file that builds a form based on a class object kept in a different script file. 
This should change the interview experience based on the user selection during the script run.

#560 NOTES - Interview - handling for different application forms

---

managed-care/enrollment-note.vbs
managed-care/enrollment.vbs

Updates to Enrollment and Enrollment Note with the correct enrollment cut off dates. 
Additionally removed United Health Care as a plan selection option.

#2015 annual enrollment update dates for 2025

---

MASTER FUNCTIONS LIBRARY.vbs
utilities/report-to-the-bzst.vbs

Func Lib needs to delete these files after a week so they don't take over. 
script end procedure with error report will include the XML as well as the TXT file
Report to the BZST script will also include the XML file in emails

#560 Handling XML files from Interview Form update

---

actions/ltc-spousal-allocation-fiater.vbs

Updated to include if statement to handle for panel update

#2087 updated actions ltc spousal fiater to align with panel update

---

bulk/find-maepd-medi-cei.vbs

Updated with if statement to align with panel updates

#2088 updated to align with panel updates

---

notices/method-b-wcom.vbs

Updated with if statement to align with panel updates.

#2089 updated method b wcom to align with panel updates

---

notes/health-care-evaluation.vbs

Make a date using the footer month and year and force it to be a date. This should create the right footer month information.

#2107 - NOTES - HC Eval - force dates to be dates

---

misc/interview-forms-classes.vbs
notes/interview.vbs

Updates to the Interview to support processing 
For ALL workers - update to the program request dialog and verbal program request details
For Interview Team:
- Identify interview team workers
- Change to Expedited Determination
- Change to the last dialog detail
- Create a specific CASE NOTE for the interview team process

Interview team functionality

---

admin/case-transfer.vbs

Updated with EMSearch to find the correct row and read the correct position based on any month/year. 
I added logic if row and col = 0  then var = "" since it was holding the previous variable value. Let me know if this should be something different.

#2091 updated bulk case transfer to align with panel updates

---

actions/ltc-icf-dd-deduction-fiater.vbs

Updated to have if statement to handle for panel update

#2086 update ltc icf dd deductions fiater to align with panel update

---

admin/resolve-hc-eomc-in-mmis.vbs

Updated with if statement to align with panel updates. I wasn't sure the best way to test this one so make sure to give it whirl.

#2090 updated resolve hc eomc in mmis with panel updates

---

deu/match-cleared.vbs

Simple variable correction which was causing the script to err.

#2038 Bug Corrected variable naming that was erroring out the script

---

COMPLETE LIST OF SCRIPTS.vbs

Assigned Usage Categories to CLOS

#2033 Assigned Usage Categories to CLOS

---

MASTER FUNCTIONS LIBRARY.vbs
nav/nav-find-maxis-case-in-mmis.vbs
nav/nav-find-mmis-pmi-in-maxis.vbs

Update both scripts to align with current scripting standards. Updated FIND MMIS PMI IN MAXIS to end at DSPL panel instead of navigating to CASE/NOTE. Updated the function navigate_to_MMIS_region to make it work with MMIS training region.

1898 NAV - FIND MMIS PMI IN MAXIS & FIND MAXIS CASE IN MMIS, update script functionality

---

notes/emergency.vbs

Received feedback from user that emergency 12-month eligibility determination should be based on the issuance date rather than the first day of the month of the issuance (i.e. using 12/15/2023 instead of 12/01/2023). Made updates to script:
- Update changelog
- Updated 12-month eligibility determination to be based on issuance date rather than first day of month of issuance
- Fixed issue with screening_determination where it was incorrectly marking a case as not eligible when the case was applying for emergency assistance again, but AFTER the end of the 12-month eligibility period
- Fixed small typos/formatting

#2129 NOTES - EMERGENCY, update 12-month determination based on issuance date 

---

notes/eligibility-summary.vbs

Added information to the error dialog and the ability to include notes about the case. 
The email will be automated to the script team. This email does not indicate that there is an error inherently, but just as a way to track these cases and this functionality.
The current information is that this FIAT and the subsequent error checking will be no longer necessary at some point in 2025, at which time all error handling can be removed. 
This will allow us more warning of future issues with this handling in using eligibility summary since the script is not designed to continue when this error is hit.

#1952 NOTES - Elig Summ - automate email if script stops for GRH error

---

deu/match-cleared.vbs

#2038 Tweaked the handling a bit

---

notes/interview.vbs

Added option to comboboxes for phone clarifications in situations where the resident pays no phone or internet bill and instead uses a free phone via the internet program. Fixed small typo.

#2141 NOTES - INTERVIEW, add free phone via internet option 

---

admin/review-report.vbs

Reactivate CASE/NOTE info regarding date of interview completion

#1799 ADMIN-Review Report- Reactivate casenoting "interview complete on xx/xx/xxxx"" 

---

admin/dail-ccd.vbs

This needed to be in an else statement
tested and working as intended

#2148 ADMIN - DAIL CCD: Updated dail_row location

---

MASTER FUNCTIONS LIBRARY.vbs

Tested and working well. I can give you a case or two (real cases) if you want to run it.

2149 fset exemption funclib

---

MASTER FUNCTIONS LIBRARY.vbs

Update 10-day cutoff dates for 2025 to address error message that workers have been seeing. TE19.132.

#2153 Update 10-day cutoff dates for 2025

---

admin/copy-case-data-for-training.vbs

We should use functions to open files and save directly to the file. Workers will need to determine that they have write access to the file.

#2160 ADMIN - Copy Case Data for Training - excel handling

---

notes/interview.vbs

Read MAXIS CASE NOTE creation to determine if the case can be edited. 
If not, a warning is given and at the end the script will stop before any actions are taken. 
Save your work functionality will support future updates once access is granted.

#2156 interview inquiry handling

---

notes/ebt-benefits-stolen.vbs

[SIR Announcement](https://www.dhssir.cty.dhs.state.mn.us/MAXIS/Lists/MAXIS%20Announcements/DispForm.aspx?ID=8563&RootFolder=/MAXIS/Lists/MAXIS%20Announcements&Source=https://www.dhssir.cty.dhs.state.mn.us/Pages/Default.aspx) indicated replacements of EBT Benefits would end on 12/20/24. Added this denial reason to the script.

#2162 NOTES - EBT BENEFITS STOLEN, update denial reasons

---

COMPLETE LIST OF SCRIPTS.vbs
admin/interview-team-cases-worklist.vbs

New script to create an excel worklist of cases with an interview completed by and Interview Team worker using the Interview script.

#2166 NEW SCRIPT - ADMIN - Interview Team Cases Worklist

---

MASTER FUNCTIONS LIBRARY.vbs

Lines with actual changes and not whitespace removal:
5365, 5417, 5509

#2173 Functions Library - Add program option to MF Orientation

---

misc/faa-health-care-information-report.vbs

Shortened 1st name read as to leave out the middle initial. Added RSEL PMI and name to output for record evaluation. Added if statement to determine which PMI to use.
Updated case status output text for accuracy.

#1920 FAA HC Information Report: Post testing updates

---

admin/training-case-creator.vbs

Also, there's a section of code for me because I don't like changing the file path when I run the training case creator.

#2183 ADMIN - Training Case Creator - mailing address coordinate update

---

misc/faa-health-care-information-report.vbs

Fingers Crossed, this is the last update. 
Added new SSN constants, default SSN match to N
Added back in SSN read in RCIP, added RSEL read
Skip logic for SSN's that are 0's and blanks.
Added output of SSN match Y/N
updated column fit ubound

#1920 MISC- FAA Health Care Information Report: Added SSN Match

---

notes/hrf.vbs

Updated script to reflect new [policy guidance](https://www.dhssir.cty.dhs.state.mn.us/Shared%20Documents/Guide%20to%20Six-Month%20Budgeting%20Final%20Version.pdf). Summary of changes:
- Added initial dialog notifying workers of changes. Includes link to guidance document
- Added handling to utilize 6-month budgeting for SNAP, GA, and MFIP from 03/25 on
- For SNAP and MFIP, the JOBS panel has error handling to ensure that the frequency is set to 1, the retrospective and prospective amounts match, and only the first line for retro and prosp amounts is filled out.
- For SNAP and MFIP, the UNEA panel has error handling to ensure that the retrospective and prospective amounts match, and only the first line for retro and prosp amounts is filled out.
- For SNAP, the BUSI panel has handling to …

#2189 NOTES - HRF, update to reflect new policy guidance

---

actions/earned-income-budgeting.vbs

My logic got a little twisted up here but this should have a better selection.

#2192 ACTION - EIB - resolve logic errors in workaround selection

---

notes/interview.vbs

Error reported when script is run from save your work.

#2187 NOTES - Interview - safety measure for addr_eff_date

---

notes/interview.vbs

Incomplete CASE/NOTE to resemble Client Contact.
Alert email to supervisors for uneditable cases.

#2210 #2211 Interview - functionality for LD Team

---

notes/interview.vbs

Confirmed this should be enough with a live test from the worker AND at test script.

#2221 NOTES - Interview - align the index in the xml output

---

notes/eligibility-summary.vbs

Updates to email notifications in Elig Summ:
- Six Month budget errors to go to supervisor
- Created function to read supervisor email from REPT/USER and the employee view
- Changed the QI member who receives 30/09 errors

#2195 & #2223 NOTES - Elig Summ 

---

MASTER FUNCTIONS LIBRARY.vbs
admin/tlr-report.vbs

Updated handling in the function ABAWD_FSET_exemption_finder in FuncLib and function BULK_ABAWD_FSET_exemption_finder in ADMIN - TLR Report to reflect person-based determination of exemptions, rather than case-based.

#2220 Update handling for RCA assessment

---

admin/on-demand-waiver-applications.vbs

Request from TP since this task has moved to JF's team.

#2230 ADMIN - On Demand Waiver - change email from TP to JF

---

notes/application-received.vbs

Updates case assignment to send pending SNAP/CASH to new pending caseloads either under currently assigned PM caseload, or assigned to random if not currently active anywher.

Update case assignment procedure for new caseloads

---

COMPLETE LIST OF SCRIPTS.vbs
admin/case-sampling.vbs

Support case review file management using a script.

#2225 ADMIN - Case Sampling - New Script

---

admin/on-demand-dashboard.vbs
admin/on-demand-waiver-applications.vbs
admin/resolve-hc-eomc-in-mmis.vbs
admin/work-assignment-from-excel.vbs

Since QI is split, we need to update the email handling within some of the scripts. 
Once this update is confirmed, we will be able to update the CLOT to reflect the correct supervisors and supervisor emails of the two different QI teams.

#2250 Update QI team email handling

---

admin/interview-team-cases-worklist.vbs

Working on getting the protection functionality to work as expected.

#2233 ADMIN - Interview Team Worklist - change protect functionality

---

admin/dail-unclear-information.vbs

Updated script to include handling for MFIP (CSES and HIRE), UHFS (CSES and HIRE), and GA (HIRE only) programs. Improved handling and functionality. Ran script through all CSES and HIRE messages.

#2168 #671 ADMIN - DAIL UNCLEAR INFO, add handling for MFIP, GA, UHFS

---

admin/case-sampling.vbs

Request from TP to update the process and allow for populations to be run on separate script runs.

#2225 ADMIN - Case Sampling - allow for second run in one day

---

admin/interview-team-cases-worklist.vbs

Need to make sure the files are only moved after they are correctly recorded.

#2233 ADMIN - Interview Team Worklist - Move files at the END

---

notes/interview.vbs

Move LD Early tracking file to after main dialog.
Update PROG functionality to remove interview dates if program does not have an APPL date.

#2235 & #2258 NOTES - Interview updates

---

utilities/all-scripts.vbs

Update script to include new details for scripts (Hot Topic link and Usage Evaluation) when writing information to Excel.

#2257 UTILITIES - ALL SCRIPTS, update to include usage eval info

---

COMPLETE LIST OF SCRIPTS.vbs

CLOS - Fix DAIL - SDX Match syntax error

#2263 CLOS - Fix DAIL - SDX Match syntax error

---

actions/earned-income-budgeting.vbs

Moved conversation/clarification field to bottom of dialog regardless of programs. Also adjusted the sizing of the GRH groupbox to better fit contents.

#2243 ACTIONS - EIB, add conversation field to dialog that applies to both SNAP and MFIP

---

admin/case-sampling.vbs

Bug reported this morning in the file creation.
Eventually discovered it was due to no comma in a long name. 
In order to find it, I had to build a way to restart the file creation.

#2225 ADMIN - Case Sampling - comma error and file create restart

---

COMPLETE LIST OF SCRIPTS.vbs
admin/health-care-pending-assignments.vbs
utilities/health-care-pending-assignments.vbs

New script for use by ADMIN and UTILITIES for pending HC assignment. 
I have done quite a bit of testing and will closely monitor a limited user group for the initial stage of testing.

#2212 ADMIN - HC Pending Assignments - New Script

---

actions/earned-income-budgeting.vbs

Changed dialog sizing and coordinates to ensure dialogs do not cut off fields.

#2278 ACTIONS - EIB, Update dialog sizing and coordinates

---

admin/interview-team-cases-worklist.vbs

If this doesn't copy correctly in the Manager Log excel - then the processor assignment is blank. 
Basically a backup for excel doing weird things.
Tested this morning.

#2233 ADMIN - Interview Cases Worklist - add excel formula if missing

---

admin/case-sampling.vbs

Adding a column to the data collected in case sampling.

#2296 ADMIN - Case Sampling - add summary field - failed list bug fix

---

notes/health-care-evaluation.vbs

Updated handling for reading BUSI panel so that if HC Method B is "0.00" instead of blank, it will display the HC Method A information.

#2287 NOTES - HC EVAL, Handle for HC Method B set to 0.00 instead of blank

---

notes/interview.vbs

Updated locations of Verifications Clear button and the return to dialog buttons to align with other dialogs.

#2299 NOTES - INTERVIEW, Update location of verif buttons to align with other dialogs

---

misc/interview-forms-classes.vbs

Resolved issue with script writing UNEA income details from dialog in CASE/NOTE but mixing up the values.

#2307 NOTES - INTERVIEW, UNEA income details mixed up in CASE/NOTE 

---

admin/interview-team-cases-worklist.vbs

Pulling in directly as I need the users to test.

#2311 - ADMIN - Interview Team Cases Worklist - folder change

---

notes/application-received.vbs

Removing North Ridge contracted facility from App Received

Removing north ridge

---

admin/case-sampling.vbs

Added an option to create a compiled report on an interval for fixing cases and evaluating reviews.

#2314 ADMIN - Case Sampling Biweekly Report Creation

---

misc/class-stat-detail.vbs
notes/health-care-evaluation.vbs

Added handling to read the OTHR panel and pull in details to assets dialog. Added field to note burial assets when they are indicated on the OTHR panel (see ONE SOURCE: [Request or Application Processing for MA-LTC Template (state.mn.us)](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=ONESOURCE-0905))

1888 NOTES - HC eval, add burial assets yes/no

---

admin/health-care-pending-assignments.vbs

Attempt to keep workers from breaking the files locks

#2212 - ADMIN - HC Pending Assignment - check for open list

---

notes/interview.vbs

Condensed information provided on expedited dialog, particularly the UNEA, housing, and utility information. This should help reduce the risk of information extending past the edge of the dialog, even when there are multiple JOBS listed.

#2317 NOTES - INTERVIEW, display issues with numerous JOBS panels 

---

admin/case-sampling.vbs

The sharepoint location has been confirmed to work for JF and her team to process and review the biweekly reports. 
This will complete the work for this issue and the task should be able to be run by TP.

#2314 ADMIN - Case Sampling - update biweekly report sharepoint folder

---

misc/interview-forms-classes.vbs
notes/interview.vbs

Interview now has better support for question formats and the version for the CAF has been updated to the 03/25 version.

#2272 CAF Form - Interview updates

---

actions/earned-income-budgeting.vbs
misc/class-stat-detail.vbs
notes/caf.vbs
notes/eligibility-summary.vbs

Updates to support the 07/01/25 MAXIS changes to support cash six-month budgeting. 
Testing and merging will occur early tomorrow.

#2340 MAXIS changes for Cash Six month Budgeting

---

MASTER FUNCTIONS LIBRARY.vbs

Update to the Read UNEA function so the scripts using it do not break. 
Does not add new functionality to read the new CASH PIC at this time.
Also fixed the indenting because my brain hated it so much.

2340 func lib coordinate changes

---

notes/expedited-determination.vbs

The UNEA panel was updated and in months 03/25 and onward has the SNAP PIC selection field moved.

#2340 NOTES - Exp Det - UNEA SNAP PIC selection moved

---

admin/dail-unclear-information.vbs
admin/mont-report.vbs
admin/review-report.vbs

Since cash six-month reporting is now working in MAIXS, there have been some more cosmetic changes that have happened to the REVW pop-ups. 
These changes are footer month specific but since the affected scripts work based on the current footer month - no conditional logic is needed. 
Currently operating well in DAIL Unclear Info - the other scripts will be tested later this month when new reports are created.

#2360 Pop-Ups on REVW Title Changes

---

notes/eligibility-summary.vbs

The user id should be the windows user ID and not the MX one.

#2333 - NOTES - ELIG Summ - USE THE RIGHT WORKER NUMBERS

---

MASTER FUNCTIONS LIBRARY.vbs
admin/ex-parte-report.vbs
admin/expedited-determination-report.vbs
admin/on-demand-dashboard.vbs
admin/on-demand-waiver-applications.vbs
admin/test-ex-parte-data-access.vbs
locally-installed-files/SETTINGS - GLOBAL VARIABLES.vbs
misc/Ex Parte/1307-Phase-1-Display-Verify-CASE-NOTE-Ex-Parte-Info.vbs
misc/Ex Parte/prep-details.vbs
notes/eligibility-summary.vbs
notes/health-care-evaluation.vbs
utilities/data-access-test.vbs

We need to centralize the identification of the DB information so that when changes occur it does not have to happen in every script individually. 
The LAN version of GlobVar has already been updated with the string and is using the defined information for the stats writing so some testing has already happened.

#2339 Add DB String to GlobVar and Call in scripts

---

MASTER FUNCTIONS LIBRARY.vbs
notes/csr.vbs

Update to UNEA and JOBS information in FuncLib to support the inclusion of information from the CASH PIC. 
Additionally, added MFIP and GA to CSR script. 
Took the opportunity to update the variable string to create a better format for this information. 
Previous UNEA Display:
New UNEA Display:
Previous JOBS Display:
New JOBS Display:

#2356 & #2367 & #2368 - UNEA and JOBS Cash PIC Supports

---

notes/caf.vbs

Resolves email error from RK.
Allows for more flexible acknowledgement of ER process on REVW to exclude only specifically SR cases.

#2374 NOTES - CAF - update REVW process determination logic

---

dail/incarceration.vbs

Updating DAIL Scrubber for ISPI matches to match the DAIL format and provide better update and view capabilities of script captured information.

#2382 DAIL - Incarceration - format and display updates

---

admin/ex-parte-report.vbs

Updates to the user ids to allow correct access to Ex Parte admin updates.

#2393 - ADMIN - Ex Parte Report - Update ADMIN allowed users

---

actions/earned-income-budgeting.vbs

Restructure of script to create a class for JOBS updates. The script is also being updated to support change in budgeting policy for Cash/UHFS/HS. 
Some of the interface is changed but the main structure of how the script operates remains the same. New format will improve maintainability of the script.

#2355 ACTIONS - EIB - create class and update for cash policy 
